import { ActionBarPrimitive, ComposerPrimitive, MessagePrimitive, ThreadPrimitive } from '@assistant-ui/react'
import { useSyncExternalStore } from 'react'
import { useTravelServices } from '../catalog/context'
const suggestions=['Show the cheapest and fastest London to Paris options next week.','Compare train and bus visually.','Plan London, Paris, and Barcelona with two and four-night stays.','Show the same options as a timeline.']
function UserMessage(){return <MessagePrimitive.Root className="travel-message travel-message-user"><div><MessagePrimitive.Parts/></div></MessagePrimitive.Root>}
function AssistantMessage(){return <MessagePrimitive.Root className="travel-message travel-message-assistant"><MessagePrimitive.Parts/><MessagePrimitive.Error><p className="travel-message-error" role="alert">The assistant could not finish this response. Retry to use your latest changes.</p></MessagePrimitive.Error><ActionBarPrimitive.Root><ActionBarPrimitive.Reload aria-label="Retry response">Retry</ActionBarPrimitive.Reload></ActionBarPrimitive.Root></MessagePrimitive.Root>}
export function ThreadShell(){
 const services=useTravelServices();const active=useSyncExternalStore(services.subscribeActive??(()=>()=>{}),services.activeId,services.activeId)
 return <div className="travel-chat"><header className="travel-chat-header"><a className="travel-brand" href="/">wayfinder</a><span className="travel-caption">Travel ideas, made yours</span></header><ThreadPrimitive.Root className="travel-thread"><ThreadPrimitive.Viewport className="travel-viewport"><ThreadPrimitive.Empty><section className="travel-welcome"><p className="travel-caption">MAKE ROOM FOR THE JOURNEY</p><h2>Where will your next<br/>good story begin?</h2><p>Compare your options, explore a different route, or build a few days away. Change any control as you go.</p><div className="travel-suggestions">{suggestions.map(prompt=><ThreadPrimitive.Suggestion key={prompt} prompt={prompt} send>{prompt}</ThreadPrimitive.Suggestion>)}</div><p className="travel-caption">All fares and totals are synthetic demo data.</p></section></ThreadPrimitive.Empty><ThreadPrimitive.Messages>{({message})=>message.role==='user'?<UserMessage/>:<AssistantMessage/>}</ThreadPrimitive.Messages></ThreadPrimitive.Viewport><div className="travel-composer-wrap"><div className="travel-active"><span>{active?`Active travel view · ${active}`:'Your next journey starts here'}</span><span>Synthetic fares</span></div><ComposerPrimitive.Root className="travel-composer"><ComposerPrimitive.Input aria-label="Message" placeholder="Ask about a route, a budget, or a few days away…" rows={2}/><ComposerPrimitive.Send aria-label="Send message">Send</ComposerPrimitive.Send><ComposerPrimitive.Cancel aria-label="Stop response">Stop</ComposerPrimitive.Cancel></ComposerPrimitive.Root></div></ThreadPrimitive.Root></div>
}
