import { useCallback, useEffect, useMemo, useState, useSyncExternalStore } from 'react'
import { Alert } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select'
import { Skeleton } from '@/components/ui/skeleton'
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { FareIdSchema, FareRowSchema, type ArtifactId,type BoundedFareFact, type FareRow } from '../../contracts'
import { legDate,tripDatesForLegDeparture } from '../../state/leg-bindings'
import { hasLoadedItineraryCoverage } from '../../state/leg-bindings'
import { withTripDates } from '../../state/ui-state-store'
import { carrierLabel,cityLabel, departure, duration, money, useArtifact, useFareRows, useTravelAction, filterPredicate } from '../context'
import type { WidgetProps } from '../layout'
import type { TravelServices } from '../context'
import { RequestNotice } from '../status/request-notice'
import { FareList } from './fare-list'
import type {DisplayRepresentation} from '../../contracts/display-context'
import type {FareItem,QueryExecutionState} from '../../contracts/query-groups'
import {fareInspectionItems,useProjectionDisplay} from '../display-records'
import {recordDisplayInteraction,useDisplayNode,usePublishDisplay} from '../display-context-provider'
import {useCalendarDays,useFareHighlights,useModeStats,useOrderedFares,useItineraryPlan} from '../context'
function fareDateTime(serviceDate:string,minutes:number){
 const day=Math.floor(minutes/1440),date=new Date(Date.parse(`${serviceDate}T00:00:00.000Z`)+day*86_400_000)
 return `${date.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})} · ${departure(minutes%1440)}`
}
function currentResourceKey(state:QueryExecutionState):string|undefined{return state.status==='ready'||state.status==='refreshing'?state.current.resourceKey:state.status==='error'?state.previous?.resourceKey:undefined}
function queryStatus(data:unknown,state:QueryExecutionState):'loading'|'ready'|'error'{return data?'ready':state.status==='error'?'error':'loading'}
function fareDisplay(items:readonly FareItem[],total:number,viewport?:{offset:number;limit:number;cursor?:string},rankOffset=0):DisplayRepresentation{const omitted=Math.max(0,total-items.length);return{payload:{kind:'fare-order',orderedFareRefs:items.map((item,index)=>({fareId:item.id,rank:rankOffset+index+1})),...(items.length?{renderedRange:{fromRank:rankOffset+1,toRank:rankOffset+items.length}}:{}),...(viewport?{viewport}:{})},totalDisplayed:total,includedCount:items.length,complete:omitted===0,omittedCount:omitted}}
function useSelection(props:WidgetProps){const {state}=useArtifact(props.artifactRef),dispatch=useTravelAction(props.artifactRef),display=useDisplayNode();return{state,toggle(item:{id:FareItem['id']}){const selected=state.selectedFareIds.includes(item.id);recordDisplayInteraction(display.store,{artifactId:props.artifactRef,componentRef:display.componentRef,action:selected?'deselect':'select'});dispatch({kind:'select',artifactId:state.artifactId,fareId:item.id,selected:!selected})}}}
export function FareCards(props:WidgetProps) {
 const node=useDisplayNode(),{services,state}=useArtifact(props.artifactRef),selection=useSelection(props),pageSize=7
 const [cursor,setCursor]=useState<string|null>(null),[cursorHistory,setCursorHistory]=useState<Array<string|null>>([])
 const result=useOrderedFares(props.artifactRef,{componentRef:node.componentRef??`${props.artifactRef}:fare-cards`,purpose:'fare-cards',datasetRef:props.datasetRef,cursor,limit:pageSize})
 const pagingIdentity=JSON.stringify({datasetRef:props.datasetRef,datasetRevision:result.requirement.datasetRevision,sourceVersion:result.requirement.sourceVersion,filters:state.filters,sort:state.sort,dates:state.dates,citySequence:state.citySequence})
 useEffect(()=>{setCursor(null);setCursorHistory([])},[pagingIdentity])
 const items=result.data?.items??[],total=result.data?.pageInfo.total??0
 const pageIndex=cursorHistory.length,rankOffset=pageIndex*pageSize
 const viewport={offset:rankOffset,limit:items.length,...(cursor?{cursor}:{})}
 useProjectionDisplay(result,fareDisplay(items,total,items.length?viewport:undefined,rankOffset),fareInspectionItems(items,new Map(),rankOffset));const status=queryStatus(result.data,result.queryState),resourceKey=currentResourceKey(result.queryState)
 if(status==='loading')return <Skeleton className="travel-skeleton" role="status">Finding your options…</Skeleton>
 if(status==='error')return <Alert className="travel-notice">These options could not load. Try refreshing the view.</Alert>
 return <Card className="travel-panel"><h3>{props.title??'Your options'}</h3><p className="travel-caption">{total} matches · Synthetic fares per passenger</p>{items.length?<FareList rowIds={items.map(item=>item.id)}>{items.map(item=>{const selected=selection.state.selectedFareIds.includes(item.id),company=carrierLabel(item,services.bridge,resourceKey);return <Card role="article" className={`travel-fare ${selected?'is-selected':''}`} key={item.id}><div><Badge className={`travel-mode travel-mode-${item.mode}`}>{cityLabel(item.mode)}</Badge><strong>{company}</strong><p>{departure(item.departureMinutes)} · {duration(item.durationMinutes)}</p><small>{cityLabel(item.originId)} → {cityLabel(item.destinationId)} · {item.serviceDate}</small></div><div><strong className="travel-price">{money(item.priceCents)}</strong><Button type="button" aria-pressed={selected} aria-label={`Select ${cityLabel(item.mode)} ${company} ${departure(item.departureMinutes)} ${money(item.priceCents)}`} onClick={()=>selection.toggle(item)}>{selected?'Selected':'Select'}</Button></div></Card>})}</FareList>:<p role="status">No options match. Try another mode, date, or price limit.</p>}<div className="travel-pagination" aria-label="Fare result pages"><Button type="button" variant="outline" disabled={!cursorHistory.length} onClick={()=>{recordDisplayInteraction(node.store,{artifactId:props.artifactRef,componentRef:node.componentRef,action:'input',inputFields:['cursor']});const previous=cursorHistory.at(-1)??null;setCursorHistory(history=>history.slice(0,-1));setCursor(previous)}}>Previous</Button><span>Page {pageIndex+1}</span><Button type="button" variant="outline" disabled={!result.data?.pageInfo.hasNextPage||!result.data.pageInfo.nextCursor} onClick={()=>{const next=result.data?.pageInfo.nextCursor;if(next){recordDisplayInteraction(node.store,{artifactId:props.artifactRef,componentRef:node.componentRef,action:'input',inputFields:['cursor']});setCursorHistory(history=>[...history,cursor]);setCursor(next)}}}>Next</Button></div></Card>
}
export function FarePicker(props:WidgetProps) {
 const node=useDisplayNode(),{services,state}=useArtifact(props.artifactRef),selection=useSelection(props),pageSize=12
 const [cursor,setCursor]=useState<string|null>(null),[cursorHistory,setCursorHistory]=useState<Array<string|null>>([])
 const result=useOrderedFares(props.artifactRef,{componentRef:node.componentRef??`${props.artifactRef}:fare-picker`,purpose:'fare-picker',datasetRef:props.datasetRef,cursor,limit:pageSize})
 const pagingIdentity=JSON.stringify({datasetRef:props.datasetRef,datasetRevision:result.requirement.datasetRevision,sourceVersion:result.requirement.sourceVersion,filters:state.filters,sort:state.sort,dates:state.dates,citySequence:state.citySequence})
 useEffect(()=>{setCursor(null);setCursorHistory([])},[pagingIdentity])
 const items=result.data?.items??[],total=result.data?.pageInfo.total??0,selected=items.find(item=>selection.state.selectedFareIds.includes(item.id))?.id??'',resourceKey=currentResourceKey(result.queryState),status=queryStatus(result.data,result.queryState),pageIndex=cursorHistory.length,rankOffset=pageIndex*pageSize
 useProjectionDisplay(result,fareDisplay(items,total,items.length?{offset:rankOffset,limit:items.length,...(cursor?{cursor}:{})}:undefined,rankOffset),fareInspectionItems(items,new Map(),rankOffset))
 const changePage=(next:string|null,direction:'previous'|'next')=>{recordDisplayInteraction(node.store,{artifactId:props.artifactRef,componentRef:node.componentRef,action:'input',inputFields:['cursor']});if(direction==='previous')setCursorHistory(history=>history.slice(0,-1));else setCursorHistory(history=>[...history,cursor]);setCursor(next)}
 return <Card className="travel-panel"><h3>{props.title??'Choose a fare'}</h3>{status==='loading'?<p role="status">Finding your options…</p>:status==='error'?<Alert>These options could not load. Try refreshing the view.</Alert>:items.length?<Label className="travel-field">Choose a synthetic fare<NativeSelect aria-label="Choose a synthetic fare" value={selected} onChange={event=>{const item=items.find(candidate=>candidate.id===event.target.value);if(item)selection.toggle(item);else if(selected)selection.toggle({id:selected})}}><NativeSelectOption value="">No fare selected on this page</NativeSelectOption>{items.map(item=><NativeSelectOption key={item.id} value={item.id}>{cityLabel(item.mode)} · {carrierLabel(item,services.bridge,resourceKey)} · {departure(item.departureMinutes)} · {duration(item.durationMinutes)} · {money(item.priceCents)}</NativeSelectOption>)}</NativeSelect></Label>:<p role="status">No options match. Try another mode, date, or price limit.</p>}<div className="travel-pagination" aria-label="Fare picker pages"><Button type="button" variant="outline" disabled={!cursorHistory.length} onClick={()=>changePage(cursorHistory.at(-1)??null,'previous')}>Previous</Button><span>Page {pageIndex+1}</span><Button type="button" variant="outline" disabled={!result.data?.pageInfo.hasNextPage||!result.data.pageInfo.nextCursor} onClick={()=>{const next=result.data?.pageInfo.nextCursor;if(next)changePage(next,'next')}}>Next</Button></div><small>Synthetic fares per passenger</small></Card>
}
export function PriceCalendar(props:WidgetProps) {
 const node=useDisplayNode(),{state}=useArtifact(props.artifactRef),dispatch=useTravelAction(props.artifactRef),selection=useSelection(props)
 const result=useCalendarDays(props.artifactRef,{componentRef:node.componentRef??`${props.artifactRef}:price-calendar`,purpose:'price-calendar',datasetRef:props.datasetRef,objective:'cheapest'}),days=(result.data?.days??[]).slice(0,62),omitted=Math.max(0,(result.data?.days.length??0)-days.length)
 const cells=days.map(day=>({key:day.date,label:day.date,value:day.representative?.priceCents,unit:(day.representative?'priceCents':'count') as 'priceCents'|'count',fareId:day.representative?.id,available:day.count>0}))
 useProjectionDisplay(result,{payload:{kind:'calendar',cells},totalDisplayed:result.data?.days.length??0,includedCount:days.length,complete:omitted===0,omittedCount:omitted},fareInspectionItems(days.flatMap(day=>day.representative?[day.representative]:[])))
 const status=queryStatus(result.data,result.queryState),origin=result.requirement.scope.originId
 if(status!=='ready')return <RequestNotice status={status} label="Date comparisons"/>
 return <Card className="travel-panel"><h3>{props.title??'Find your best day'}</h3><div className="travel-calendar">{days.map(day=>{const item=day.representative,selected=item?selection.state.selectedFareIds.includes(item.id):false;return <div className={`travel-calendar-option${selected?' is-selected':''}`} key={day.date}><Button variant="outline" type="button" disabled={!item} onClick={()=>{if(item)dispatch({kind:'calendarDates',artifactId:state.artifactId,dates:tripDatesForLegDeparture(state,origin,day.date)})}}><span>{new Date(`${day.date}T12:00:00`).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}</span><strong>{item?money(item.priceCents):'No fare'}</strong><small>{day.count} options</small></Button>{item&&<Button type="button" size="sm" variant={selected?'default':'outline'} aria-pressed={selected} aria-label={`${selected?'Remove':'Add'} cheapest fare on ${day.date} ${selected?'from':'to'} trip`} onClick={()=>selection.toggle(item)}>{selected?'Added':'Add cheapest'}</Button>}</div>})}</div>{!days.length&&<p role="status">No options match. Try another mode, date, or price limit.</p>}</Card>
}
export function Comparison(props:WidgetProps) {
 const node=useDisplayNode(),result=useModeStats(props.artifactRef,{componentRef:node.componentRef??`${props.artifactRef}:comparison`,purpose:'comparison-matrix',datasetRef:props.datasetRef,baseline:'active'}),modes=result.data?.modes??[]
 const cells=modes.flatMap(mode=>[{key:`${mode.mode}-price`,label:`${mode.mode} minimum fare`,value:mode.minPriceCents??undefined,unit:'priceCents' as const},{key:`${mode.mode}-duration`,label:`${mode.mode} fastest`,value:mode.minDurationMinutes??undefined,unit:'durationMinutes' as const},{key:`${mode.mode}-count`,label:`${mode.mode} options`,value:mode.count,unit:'count' as const}])
 useProjectionDisplay(result,{payload:{kind:'aggregate',cells},totalDisplayed:cells.length,includedCount:cells.length,complete:true,omittedCount:0})
 const status=queryStatus(result.data,result.queryState);if(status!=='ready')return <RequestNotice status={status} label="Mode comparisons"/>
 return <Card className="travel-panel"><h3>{props.title??'Compare your way there'}</h3><div className="travel-table-wrap"><Table><TableCaption>Synthetic fares per passenger</TableCaption><TableHeader><TableRow><TableHead scope="col">Mode</TableHead><TableHead scope="col">From</TableHead><TableHead scope="col">Fastest</TableHead><TableHead scope="col">Options</TableHead></TableRow></TableHeader><TableBody>{modes.map(mode=><TableRow key={mode.mode}><TableHead scope="row">{cityLabel(mode.mode)}</TableHead><TableCell>{mode.minPriceCents===null?'–':money(mode.minPriceCents)}</TableCell><TableCell>{mode.minDurationMinutes===null?'–':duration(mode.minDurationMinutes)}</TableCell><TableCell>{mode.count}</TableCell></TableRow>)}</TableBody></Table></div>{!modes.length&&<p role="status">No options match. Try another mode, date, or price limit.</p>}</Card>
}
function useSelectedFacts(ref:string){
 const plan=useItineraryPlan(ref)
 return{services:plan.services,state:plan.state,result:plan.status==='ready'?{status:'ready' as const,facts:plan.facts}:{status:'loading' as const}}
}
export function Total(props:WidgetProps) {
 const {services,state,result}=useSelectedFacts(props.artifactRef)
 const passengers=state.datasetRefs[0]?services.bridge.findBinding(state.datasetRefs[0])?.manifest.coverage.passengers??1:1
 const total=result.status==='ready'?result.facts.reduce((sum,f)=>sum+f.priceCents,0)*passengers:0,facts=result.status==='ready'?result.facts:[]
 usePublishDisplay({display:{payload:{kind:'selection',orderedFareRefs:facts.map((fact,index)=>({fareId:fact.id,rank:index+1})),totalPriceCents:total,passengers},totalDisplayed:state.selectedFareIds.length,includedCount:facts.length,complete:facts.length===state.selectedFareIds.length,omittedCount:Math.max(0,state.selectedFareIds.length-facts.length)}})
 return <Card className="travel-total"><span>{props.title??'Synthetic total'}</span>{result.status!=='ready'?<RequestNotice status={result.status} label="Selected fares"/>:<><strong>{money(total)}</strong><p>{passengers} passenger{passengers===1?'':'s'}</p></>}<small>Synthetic total, including demo fees. No booking is available.</small></Card>
}
export function SelectedItinerary(props:WidgetProps) {
 const {state,result}=useSelectedFacts(props.artifactRef),facts=result.status==='ready'?result.facts:[]
 usePublishDisplay({display:{payload:{kind:'selection',orderedFareRefs:facts.map((fact,index)=>({fareId:fact.id,rank:index+1}))},totalDisplayed:state.selectedFareIds.length,includedCount:facts.length,complete:facts.length===state.selectedFareIds.length,omittedCount:Math.max(0,state.selectedFareIds.length-facts.length)}})
 return <Card className="travel-panel" role="region" aria-label="Selected itinerary"><h3>{props.title??'Selected fares'}</h3>{result.status!=='ready'?<RequestNotice status={result.status} label="Selected fares"/>:result.facts.length?<ol className="travel-timeline">{result.facts.map(fact=><li key={fact.id}><strong>{cityLabel(fact.originId)} → {cityLabel(fact.destinationId)}</strong><span>{fact.serviceDate} · {cityLabel(fact.mode)} · {money(fact.priceCents)} per passenger</span></li>)}</ol>:<p role="status">Choose a fare to see your itinerary.</p>}</Card>
}
export function ComparisonTable(props:WidgetProps) {
 const node=useDisplayNode(),{services,state}=useArtifact(props.artifactRef),selection=useSelection(props),pageSize=10
 const [cursor,setCursor]=useState<string|null>(null),[cursorHistory,setCursorHistory]=useState<Array<string|null>>([])
 const result=useOrderedFares(props.artifactRef,{componentRef:node.componentRef??`${props.artifactRef}:comparison-table`,purpose:'comparison-table',datasetRef:props.datasetRef,cursor,limit:pageSize})
 const pagingIdentity=JSON.stringify({datasetRef:props.datasetRef,datasetRevision:result.requirement.datasetRevision,sourceVersion:result.requirement.sourceVersion,filters:state.filters,sort:state.sort,dates:state.dates,citySequence:state.citySequence})
 useEffect(()=>{setCursor(null);setCursorHistory([])},[pagingIdentity])
 const items=result.data?.items??[],total=result.data?.pageInfo.total??0,resourceKey=currentResourceKey(result.queryState),pageIndex=cursorHistory.length,rankOffset=pageIndex*pageSize
 useProjectionDisplay(result,fareDisplay(items,total,items.length?{offset:rankOffset,limit:items.length,...(cursor?{cursor}:{})}:undefined,rankOffset),fareInspectionItems(items,new Map(),rankOffset));const status=queryStatus(result.data,result.queryState);if(status!=='ready')return <RequestNotice status={status} label="Fare comparisons"/>
 return <Card className="travel-panel"><h3>{props.title??'Compare fares'}</h3><div className="travel-table-wrap"><Table aria-label="Compare fares"><TableCaption>Synthetic fares per passenger</TableCaption><TableHeader><TableRow><TableHead>Mode</TableHead><TableHead>Carrier</TableHead><TableHead>Date</TableHead><TableHead>Departure</TableHead><TableHead>Duration</TableHead><TableHead>Fare</TableHead><TableHead>Trip</TableHead></TableRow></TableHeader><TableBody>{items.map(item=>{const selected=selection.state.selectedFareIds.includes(item.id);return <TableRow key={item.id}><TableHead scope="row">{cityLabel(item.mode)}</TableHead><TableCell>{carrierLabel(item,services.bridge,resourceKey)}</TableCell><TableCell>{item.serviceDate}</TableCell><TableCell>{departure(item.departureMinutes)}</TableCell><TableCell>{duration(item.durationMinutes)}</TableCell><TableCell>{money(item.priceCents)}</TableCell><TableCell><Button type="button" size="sm" variant={selected?'default':'outline'} aria-pressed={selected} aria-label={`${selected?'Remove':'Add'} ${cityLabel(item.mode)} ${money(item.priceCents)} ${selected?'from':'to'} trip`} onClick={()=>selection.toggle(item)}>{selected?'Added':'Add'}</Button></TableCell></TableRow>})}</TableBody></Table></div>{!items.length&&<p role="status">No options match. Try another mode, date, or price limit.</p>}<div className="travel-pagination" aria-label="Comparison result pages"><Button type="button" variant="outline" disabled={!cursorHistory.length} onClick={()=>{recordDisplayInteraction(node.store,{artifactId:props.artifactRef,componentRef:node.componentRef,action:'input',inputFields:['cursor']});const previous=cursorHistory.at(-1)??null;setCursorHistory(history=>history.slice(0,-1));setCursor(previous)}}>Previous</Button><span>Page {pageIndex+1}</span><Button type="button" variant="outline" disabled={!result.data?.pageInfo.hasNextPage||!result.data.pageInfo.nextCursor} onClick={()=>{const next=result.data?.pageInfo.nextCursor;if(next){recordDisplayInteraction(node.store,{artifactId:props.artifactRef,componentRef:node.componentRef,action:'input',inputFields:['cursor']});setCursorHistory(history=>[...history,cursor]);setCursor(next)}}}>Next</Button></div></Card>
}
export function ModeBreakdown(props:WidgetProps) {
 const node=useDisplayNode(),result=useModeStats(props.artifactRef,{componentRef:node.componentRef??`${props.artifactRef}:mode-breakdown`,purpose:'mode-breakdown',datasetRef:props.datasetRef,baseline:'active'}),modes=result.data?.modes??[],cells=modes.map(mode=>({key:mode.mode,label:cityLabel(mode.mode),value:mode.count,unit:'count' as const}))
 useProjectionDisplay(result,{payload:{kind:'aggregate',cells},totalDisplayed:cells.length,includedCount:cells.length,complete:true,omittedCount:0});const status=queryStatus(result.data,result.queryState);if(status!=='ready')return <RequestNotice status={status} label="Mode counts"/>
 return <Card className="travel-panel"><h3>{props.title??'Options by mode'}</h3><div className="travel-table-wrap"><Table aria-label="Options by mode"><TableHeader><TableRow><TableHead scope="col">Mode</TableHead><TableHead scope="col">Options</TableHead></TableRow></TableHeader><TableBody>{modes.map(mode=><TableRow key={mode.mode}><TableHead scope="row">{cityLabel(mode.mode)}</TableHead><TableCell>{mode.count}</TableCell></TableRow>)}</TableBody></Table></div>{!modes.length&&<p role="status">No options match. Try another mode, date, or price limit.</p>}</Card>
}

export function Coverage(props:WidgetProps) {
 const {services,state}=useArtifact(props.artifactRef),bindings=state.datasetRefs.flatMap(id=>{const binding=services.bridge.findBinding(id);return binding?[binding]:[]}),entries=bindings.map(binding=>({resourceKey:binding.resourceKey,complete:binding.manifest.complete,truncated:!binding.manifest.complete,totalAvailable:binding.manifest.totalAvailable}))
 usePublishDisplay({display:{payload:{kind:'coverage',entries},totalDisplayed:entries.length,includedCount:entries.length,complete:true,omittedCount:0}})
 return <Alert className="travel-notice" role="status" aria-atomic="true"><strong>{props.title??'Travel data scope'}</strong>{!bindings.length&&<p>No travel scope is loaded. Add stops in your next message.</p>}{bindings.map(binding=><p key={binding.resourceKey}>{binding.manifest.complete?'Complete server scope':binding.manifest.availableDateWindow===null?'No fares in the requested coverage window':'Partial server scope'} · {cityLabel(binding.manifest.coverage.originId)} → {cityLabel(binding.manifest.coverage.destinationId)} · {binding.manifest.coverage.dateWindow.from} to {binding.manifest.coverage.dateWindow.to} · {binding.manifest.totalAvailable.toLocaleString()} matching synthetic options</p>)}</Alert>
}
function useRouteStops(ref:string) {
 const {state}=useArtifact(ref)
 return state.citySequence.map((cityId,index)=>({cityId,nights:index===0?0:state.stays.find(stay=>stay.cityId===cityId)?.nights??0}))
}
export function CitySequence(props:WidgetProps) {
 const stops=useRouteStops(props.artifactRef)
 usePublishDisplay({display:{payload:{kind:'route',cityIds:stops.map(stop=>stop.cityId)},totalDisplayed:stops.length,includedCount:stops.length,complete:true,omittedCount:0}})
 return <Card className="travel-panel"><h3>{props.title??'Your stops'}</h3>{!stops.length&&<p role="status">Add stops in your next message to see your route.</p>}<ol className="travel-timeline" aria-label="Travel stops">{stops.map((stop,index)=><li key={`${stop.cityId}-${index}`}><strong>{cityLabel(stop.cityId)}</strong>{stop.nights>0&&<span>{stop.nights} night{stop.nights===1?'':'s'}</span>}</li>)}</ol></Card>
}
export function Route(props:WidgetProps) {
 const cities=useRouteStops(props.artifactRef).map(stop=>stop.cityId)
 usePublishDisplay({display:{payload:{kind:'route',cityIds:cities},totalDisplayed:cities.length,includedCount:cities.length,complete:true,omittedCount:0}})
 return <Card className="travel-panel"><h3>{props.title??'Your route'}</h3>{!cities.length?<p role="status">Add stops in your next message to see your route.</p>:<><svg viewBox="0 0 600 135" role="img" aria-label={`Schematic route: ${cities.map(cityLabel).join(' to ')}`}><path d="M45 55H555" stroke="var(--travel-blue)" strokeWidth="3" fill="none"/>{cities.map((city,i)=>{const x=45+i*510/Math.max(1,cities.length-1);return <g key={`${city}-${i}`}><circle cx={x} cy="55" r="9" fill="var(--travel-blue)"/><text x={x} y="92" textAnchor="middle">{cityLabel(city)}</text></g>})}</svg><small>Schematic route, not a geographic map.</small></>}</Card>
}
export function Timeline(props:WidgetProps) {
 const node=useDisplayNode(),result=useOrderedFares(props.artifactRef,{componentRef:node.componentRef??`${props.artifactRef}:timeline`,purpose:'itinerary-timeline',datasetRef:props.datasetRef,limit:5}),selected=useSelectedFacts(props.artifactRef),selection=useSelection(props),queryItems=result.data?.items??[],total=result.data?.pageInfo.total??0
 useProjectionDisplay(result,fareDisplay(queryItems,total),fareInspectionItems(queryItems));const status=selected.state.selectedFareIds.length?selected.result.status:queryStatus(result.data,result.queryState)
 if(status!=='ready')return <RequestNotice status={status} label="Journey details"/>
 const rows=selected.result.status==='ready'&&selected.result.facts.length?selected.result.facts:queryItems
 return <Card className="travel-panel"><h3>{props.title??'Journey timeline'}</h3><RequestNotice status="ready" empty={!rows.length}/><ol className="travel-timeline">{rows.map(row=>{const isSelected=selection.state.selectedFareIds.includes(row.id);return <li key={row.id}><span>{row.serviceDate} · {departure(row.departureMinutes)}</span><strong>{cityLabel(row.originId)} → {cityLabel(row.destinationId)}</strong><p>{cityLabel(row.mode)} · {duration(row.durationMinutes)} · {money(row.priceCents)}</p><Button type="button" size="sm" variant={isSelected?'default':'outline'} aria-pressed={isSelected} aria-label={`${isSelected?'Remove':'Add'} ${cityLabel(row.mode)} ${money(row.priceCents)} ${isSelected?'from':'to'} trip`} onClick={()=>selection.toggle(row)}>{isSelected?'Added':'Add to trip'}</Button></li>})}</ol></Card>
}
export function Plot(props:WidgetProps) {
 const node=useDisplayNode(),{services}=useArtifact(props.artifactRef),selection=useSelection(props),result=useOrderedFares(props.artifactRef,{componentRef:node.componentRef??`${props.artifactRef}:plot`,purpose:'duration-price-plot',datasetRef:props.datasetRef,limit:50}),items=result.data?.items??[],total=result.data?.pageInfo.total??0,maxPrice=Math.max(1,...items.map(item=>item.priceCents)),maxDuration=Math.max(1,...items.map(item=>item.durationMinutes)),resourceKey=currentResourceKey(result.queryState)
 useProjectionDisplay(result,{payload:{kind:'plot',orderedFareRefs:items.map((item,index)=>({fareId:item.id,rank:index+1}))},totalDisplayed:total,includedCount:items.length,complete:total===items.length,omittedCount:Math.max(0,total-items.length)},fareInspectionItems(items));const status=queryStatus(result.data,result.queryState);if(status!=='ready')return <RequestNotice status={status} label="Journey comparisons"/>
 return <Card className="travel-panel"><h3>{props.title??'Price and journey time'}</h3><RequestNotice status="ready" empty={!items.length}/><p className="travel-caption">Left is faster · lower is cheaper · choose a point to add or remove it</p><svg viewBox="0 0 450 260" role="group" aria-label="Duration and price comparison"><path d="M45 15V225H440" fill="none" stroke="currentColor"/>{items.map(item=>{const selected=selection.state.selectedFareIds.includes(item.id),toggle=()=>selection.toggle(item);return <Button asChild key={item.id}><circle cx={45+item.durationMinutes/maxDuration*370} cy={220-item.priceCents/maxPrice*180} r="7" className={`travel-dot travel-mode-${item.mode}`} role="button" tabIndex={0} aria-pressed={selected} aria-label={`${selected?'Remove':'Add'} ${cityLabel(item.mode)} ${duration(item.durationMinutes)} ${money(item.priceCents)} ${selected?'from':'to'} trip`} onClick={toggle} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}}}><title>{carrierLabel(item,services.bridge,resourceKey)}</title></circle></Button>})}<text x="220" y="253">Journey duration</text></svg></Card>
}
export function CheapestFastest(props:WidgetProps) {
 const node=useDisplayNode(),{services}=useArtifact(props.artifactRef),selection=useSelection(props),result=useFareHighlights(props.artifactRef,{componentRef:node.componentRef??`${props.artifactRef}:highlights`,purpose:'fare-highlights',datasetRef:props.datasetRef}),highlights=[{name:'Lowest fare',row:result.data?.cheapest??undefined},{name:'Fastest journey',row:result.data?.fastest??undefined}],items=highlights.flatMap(item=>item.row?[item.row]:[]),resourceKey=currentResourceKey(result.queryState)
 useProjectionDisplay(result,{payload:{kind:'fare-highlights',items:highlights.map(item=>({label:item.name,fareId:item.row?.id}))},totalDisplayed:items.length,includedCount:items.length,complete:true,omittedCount:0},fareInspectionItems(items,new Map(highlights.flatMap(item=>item.row?[[item.row.id,item.name]]:[]))));const status=queryStatus(result.data,result.queryState)
 if(status!=='ready')return <RequestNotice status={status} label="Fare comparisons"/>
 return <Card className="travel-panel"><h3>{props.title??'Cheapest and fastest'}</h3><RequestNotice status="ready" empty={!items.length}/><div className="travel-responsivegrid">{highlights.map(({name,row})=>{const selected=row?selection.state.selectedFareIds.includes(row.id):false;return <Card className={`travel-insight${selected?' is-selected':''}`} key={name}><span>{name}</span><strong>{row?money(row.priceCents):'No match'}</strong><p>{row?`${duration(row.durationMinutes)} · ${cityLabel(row.mode)}`:''}</p>{row&&<dl className="travel-insight-details"><div><dt>Company</dt><dd>{carrierLabel(row,services.bridge,resourceKey)}</dd></div><div><dt>Departure</dt><dd>{fareDateTime(row.serviceDate,row.departureMinutes)}</dd></div><div><dt>Arrival</dt><dd>{fareDateTime(row.serviceDate,row.departureMinutes+row.durationMinutes)}</dd></div></dl>}{row&&<Button type="button" variant={selected?'default':'outline'} aria-pressed={selected} aria-label={`${selected?'Remove':'Add'} ${name.toLocaleLowerCase()} ${cityLabel(row.mode)} ${money(row.priceCents)} ${selected?'from':'to'} trip`} onClick={()=>selection.toggle(row)}>{selected?'Added':'Add to trip'}</Button>}</Card>})}</div></Card>
}

export function SelectedFareCount(props:WidgetProps) {
 const {state}=useArtifact(props.artifactRef)
 const count=state.selectedFareIds.length
 usePublishDisplay({display:{payload:{kind:'selection',orderedFareRefs:state.selectedFareIds.map((fareId,index)=>({fareId,rank:index+1}))},totalDisplayed:count,includedCount:count,complete:true,omittedCount:0}})
 return <Badge className="travel-caption" role="status" aria-label="Selected fares" aria-atomic="true">{count} selected fare{count===1?'':'s'}</Badge>
}
