import { useEffect, useState } from 'react'
import { type BoundedFareFact } from '../../contracts'
import { cityLabel, departure, duration, money, useArtifact, useFareRows, useTravelAction, useTravelQuery, filterPredicate } from '../context'
import type { WidgetProps } from '../layout'
export function FareCards(props:WidgetProps) {
 const result=useFareRows(props.artifactRef,props.datasetRef); const dispatch=useTravelAction(props.artifactRef)
 if(result.status==='loading')return <div className="travel-skeleton" role="status">Finding your options…</div>
 if(result.status==='error')return <div role="alert" className="travel-notice">These options could not load. Try refreshing the view.</div>
 return <section className="travel-panel"><h3>{props.title??'Your options'}</h3><p className="travel-caption">{result.data?.total??0} matches · Synthetic fares per passenger</p>{result.rows.length?<div className="travel-fares">{result.rows.slice(0,20).map(row=><article className={`travel-fare ${result.state.selectedFareIds.includes(row.id)?'is-selected':''}`} key={row.id}><div><span className={`travel-mode travel-mode-${row.mode}`}>{cityLabel(row.mode)}</span><strong>{cityLabel(row.carrierId)}</strong><p>{departure(row.departureMinutes)} · {duration(row.durationMinutes)}</p><small>{cityLabel(row.originId)} → {cityLabel(row.destinationId)} · {row.serviceDate}</small></div><div><strong className="travel-price">{money(row.priceCents)}</strong><button type="button" aria-pressed={result.state.selectedFareIds.includes(row.id)} aria-label={`Select ${cityLabel(row.mode)} ${cityLabel(row.carrierId)} ${departure(row.departureMinutes)} ${money(row.priceCents)}`} onClick={()=>dispatch({kind:'select',artifactId:result.state.artifactId,fareId:row.id,selected:!result.state.selectedFareIds.includes(row.id)})}>{result.state.selectedFareIds.includes(row.id)?'Selected':'Select'}</button></div></article>)}</div>:<p role="status">No options match. Try another mode, date, or price limit.</p>}{(result.data?.total??0)>20&&<p className="travel-caption">Showing the first 20. Narrow your filters to compare more closely.</p>}</section>
}
export function PriceCalendar(props:WidgetProps) {
 const result=useTravelQuery(props.artifactRef,props.datasetRef,(state,id)=>({version:1,sources:[{datasetRef:id,alias:'f'}],where:filterPredicate(state,false),groupBy:['serviceDate'],metrics:[{as:'minimum',op:'min',field:'priceCents'},{as:'count',op:'count'}],orderBy:[{field:'serviceDate',direction:'asc'}],limit:30}));const dispatch=useTravelAction(props.artifactRef)
 return <section className="travel-panel"><h3>{props.title??'Find your best day'}</h3><div className="travel-calendar">{result.data?.rows.map(row=>typeof row.serviceDate==='string'&&typeof row.minimum==='number'?<button key={row.serviceDate} type="button" aria-pressed={result.state.dates.start===row.serviceDate} onClick={()=>{if(typeof row.serviceDate==='string')dispatch({kind:'dates',artifactId:result.state.artifactId,dates:{...result.state.dates,start:row.serviceDate}})}}><span>{new Date(`${row.serviceDate}T12:00:00`).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}</span><strong>{money(row.minimum)}</strong><small>{row.count} options</small></button>:null)}</div>{result.status==='loading'&&<p role="status">Comparing dates…</p>}{result.status==='ready'&&!result.data?.rows.length&&<p role="status">No options match. Try another mode, date, or price limit.</p>}</section>
}
export function Comparison(props:WidgetProps) {
 const result=useTravelQuery(props.artifactRef,props.datasetRef,(state,id)=>({version:1,sources:[{datasetRef:id,alias:'f'}],where:filterPredicate(state),groupBy:['mode'],metrics:[{as:'minimum',op:'min',field:'priceCents'},{as:'fastest',op:'min',field:'durationMinutes'},{as:'count',op:'count'}],limit:4}));
 return <section className="travel-panel"><h3>{props.title??'Compare your way there'}</h3><div className="travel-table-wrap"><table><caption>Synthetic fares per passenger</caption><thead><tr><th scope="col">Mode</th><th scope="col">From</th><th scope="col">Fastest</th><th scope="col">Options</th></tr></thead><tbody>{result.data?.rows.map(row=><tr key={String(row.mode)}><th scope="row">{cityLabel(String(row.mode))}</th><td>{typeof row.minimum==='number'?money(row.minimum):'–'}</td><td>{typeof row.fastest==='number'?duration(row.fastest):'–'}</td><td>{row.count}</td></tr>)}</tbody></table></div>{result.status==='ready'&&!result.data?.rows.length&&<p role="status">No options match. Try another mode, date, or price limit.</p>}</section>
}
function useSelectedFacts(ref:string){
 const {services,state}=useArtifact(ref);const [facts,setFacts]=useState<BoundedFareFact[]>([]);const selected=JSON.stringify(state.selectedFareIds)
 useEffect(()=>{let active=true;Promise.all(state.selectedFareIds.map(id=>services.bridge.lookupFare(id,[]))).then(items=>{if(active)setFacts(items)}).catch(()=>{if(active)setFacts([])});return()=>{active=false}},[services.bridge,selected])
 return{services,state,facts}
}
export function Total(props:WidgetProps&{detail?:boolean}) {
 const {services,state,facts}=useSelectedFacts(props.artifactRef)
 const passengers=state.datasetRefs[0]?services.bridge.getManifest(state.datasetRefs[0]).coverage.passengers:1
 return <section className="travel-total"><span>{props.title??'Your selected trip'}</span><strong>{money(facts.reduce((sum,f)=>sum+f.priceCents,0)*passengers)}</strong><p>{facts.length} selected leg{facts.length===1?'':'s'} · {passengers} passenger{passengers===1?'':'s'}</p><small>Synthetic total, including demo fees. No booking is available.</small>{props.detail&&<ol className="travel-timeline">{facts.map(fact=><li key={fact.id}><strong>{cityLabel(fact.originId)} → {cityLabel(fact.destinationId)}</strong><span>{fact.serviceDate} · {cityLabel(fact.mode)} · {money(fact.priceCents)} per passenger</span></li>)}</ol>}</section>
}
export function Coverage(props:WidgetProps) {
 const {services,state}=useArtifact(props.artifactRef); const manifests=state.datasetRefs.map(id=>services.bridge.getManifest(id))
 return <section className="travel-notice"><strong>{props.title??'Loaded travel data'}</strong>{manifests.map(m=><p key={m.datasetId}>{m.coverage.complete?'Complete':'Partial'} · {cityLabel(m.coverage.originIds.join(', '))} → {cityLabel(m.coverage.destinationIds.join(', '))} · {m.coverage.dateWindow.from} to {m.coverage.dateWindow.to} · {m.rowCount.toLocaleString()} synthetic fares</p>)}</section>
}
export function Route(props:WidgetProps) {
 const {services,state}=useArtifact(props.artifactRef);const legs=state.datasetRefs.map(id=>services.bridge.getManifest(id).coverage);const distinct=legs.filter((leg,index)=>legs.findIndex(other=>other.originIds[0]===leg.originIds[0]&&other.destinationIds[0]===leg.destinationIds[0])===index);const cities=distinct.length?[distinct[0].originIds[0],...distinct.map(l=>l.destinationIds[0])].filter((c):c is string=>typeof c==='string'):[]
 return <section className="travel-panel"><h3>{props.title??'Your route'}</h3><svg viewBox="0 0 600 135" role="img" aria-label={`Schematic route: ${cities.map(cityLabel).join(' to ')}`}><path d="M45 55H555" stroke="var(--travel-blue)" strokeWidth="3" fill="none"/>{cities.map((city,i)=>{const x=45+i*510/Math.max(1,cities.length-1);return <g key={`${city}-${i}`}><circle cx={x} cy="55" r="9" fill="var(--travel-blue)"/><text x={x} y="92" textAnchor="middle">{cityLabel(city)}</text></g>})}</svg><small>Schematic route, not a geographic map.</small></section>
}
export function Timeline(props:WidgetProps) {
 const result=useFareRows(props.artifactRef,props.datasetRef);const selected=useSelectedFacts(props.artifactRef);const rows=selected.facts.length?selected.facts:result.rows.slice(0,5)
 return <section className="travel-panel"><h3>{props.title??'Journey timeline'}</h3><ol className="travel-timeline">{rows.map(row=><li key={row.id}><span>{row.serviceDate} · {departure(row.departureMinutes)}</span><strong>{cityLabel(row.originId)} → {cityLabel(row.destinationId)}</strong><p>{cityLabel(row.mode)} · {duration(row.durationMinutes)} · {money(row.priceCents)}</p></li>)}</ol></section>
}
export function Plot(props:WidgetProps) {
 const result=useFareRows(props.artifactRef,props.datasetRef);const maxPrice=Math.max(1,...result.rows.map(r=>r.priceCents));const maxDuration=Math.max(1,...result.rows.map(r=>r.durationMinutes));const dispatch=useTravelAction(props.artifactRef)
 return <section className="travel-panel"><h3>{props.title??'Price and journey time'}</h3><p className="travel-caption">Left is faster · lower is cheaper · choose a point to select</p><svg viewBox="0 0 450 260" role="group" aria-label="Duration and price comparison"><path d="M45 15V225H440" fill="none" stroke="currentColor"/>{result.rows.slice(0,50).map(row=><circle key={row.id} cx={45+row.durationMinutes/maxDuration*370} cy={220-row.priceCents/maxPrice*180} r="7" className={`travel-dot travel-mode-${row.mode}`} role="button" tabIndex={0} aria-label={`${cityLabel(row.mode)} ${duration(row.durationMinutes)} ${money(row.priceCents)}`} onClick={()=>dispatch({kind:'select',artifactId:result.state.artifactId,fareId:row.id,selected:true})} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();dispatch({kind:'select',artifactId:result.state.artifactId,fareId:row.id,selected:true})}}}><title>{cityLabel(row.carrierId)}</title></circle>)}<text x="220" y="253">Journey duration</text></svg></section>
}
export function CheapestFastest(props:WidgetProps) {
 const cheapest=useTravelQuery(props.artifactRef,props.datasetRef,(state,id)=>({version:1,sources:[{datasetRef:id,alias:'f'}],where:filterPredicate(state),orderBy:[{field:'priceCents',direction:'asc'}],limit:1}));const fastest=useTravelQuery(props.artifactRef,props.datasetRef,(state,id)=>({version:1,sources:[{datasetRef:id,alias:'f'}],where:filterPredicate(state),orderBy:[{field:'durationMinutes',direction:'asc'}],limit:1}))
 return <section className="travel-panel"><h3>{props.title??'Cheapest and fastest'}</h3><div className="travel-responsivegrid">{[{name:'Lowest fare',row:cheapest.data?.rows[0]},{name:'Fastest journey',row:fastest.data?.rows[0]}].map(({name,row})=><div className="travel-insight" key={name}><span>{name}</span><strong>{row&&typeof row.priceCents==='number'?money(row.priceCents):'No match'}</strong><p>{row&&typeof row.durationMinutes==='number'?duration(row.durationMinutes):''} {row?cityLabel(String(row.mode)):''}</p></div>)}</div></section>
}
