import{validateReviewExport}from'/review/export-validation.mjs';
const packet=await(await fetch('/manifest.json')).json(),draft=await(await fetch('/ratings-template.json')).json(),byToken=new Map(draft.reviews.map(review=>[review.token,review]));
const find=id=>document.getElementById(id),select=find('item'),status=find('status'),frame=find('interactive');
find('source').textContent=`Anonymous reviewer ${packet.participant} · App freeze ${packet.sourceFreeze.runtime.appRevision} · Synthetic fare source ${packet.sourceFreeze.fixture.sourceVersion}`;
for(const[itemIndex,item]of packet.items.entries()){const option=document.createElement('option');option.value=item.token;option.textContent=`Case ${item.caseId.slice(5)} · Round ${item.round}`;select.append(option);if(itemIndex===0)select.value=item.token;}
for(const dimension of packet.dimensions){const label=document.createElement('label');label.textContent=dimension;const input=document.createElement('select');input.dataset.dimension=dimension;input.setAttribute('aria-label',dimension);for(const value of['',1,2,3,4,5]){const option=document.createElement('option');option.value=String(value);option.textContent=value===''?'Unrated':String(value);input.append(option);}label.append(input);find('ratings').append(label);}
const ratingInputs=[...find('ratings').querySelectorAll('select')],notes=find('notes').querySelector('textarea');let current;
function save(){if(!current)return;const entry=byToken.get(current.token);entry.captureReviewed=find('capture-reviewed').checked;entry.handsOnAttempted=find('hands-on').checked;entry.notes=notes.value;for(const input of ratingInputs)entry.ratings[input.dataset.dimension]=input.value===''?null:Number(input.value);}
function show(){save();current=packet.items.find(item=>item.token===select.value);const entry=byToken.get(current.token);find('title').textContent=`Case ${current.caseId.slice(5)} · Round ${current.round}`;find('task').textContent=current.task;find('instructions').textContent=current.instructions;status.textContent=current.status==='recorded completion failed'?'Recorded generation did not complete successfully. Review the available evidence and note its limits.':current.status==='not collected'?'No machine cell was collected for this round.':'';find('instructions').textContent=current.instructions;find('capture').hidden=!current.captureAvailable;if(current.captureAvailable)find('capture').src='/'+current.capture;find('capture-status').textContent=current.captureAvailable?'':'No capture was collected for this item. Do not infer its visual quality.';find('capture-reviewed').disabled=!current.captureAvailable;find('capture-reviewed').checked=entry.captureReviewed;find('hands-on').disabled=!current.artifactAvailable;find('hands-on').checked=entry.handsOnAttempted;find('open').disabled=!current.artifactAvailable;find('reload').disabled=true;find('interactive-status').textContent=current.artifactAvailable?'Open the view to attempt the task.':'No usable native artifact was collected. Describe this limitation in notes; do not invent a score.';notes.value=entry.notes;for(const input of ratingInputs)input.value=String(entry.ratings[input.dataset.dimension]??'');frame.hidden=true;frame.src='about:blank';}
async function activate(reload=false){const token=current.token;if(!reload){frame.hidden=true;frame.src='about:blank';}find('open').disabled=true;status.textContent='Restoring recorded travel view with its original fare resources…';try{const response=await fetch(`/activate/${token}${reload?'?reload=1':''}`,{method:'POST'});const result=await response.json();if(!response.ok)throw new Error(result.error);if(current.token!==token)return;frame.src=`/interactive/${token}`;frame.hidden=false;find('reload').disabled=false;status.textContent='Interactive view ready. Try the task before checking hands-on completion.';}catch{status.textContent='This replay is unavailable or its source changed. Leave unsupported dimensions unrated and describe the limitation.';}finally{find('open').disabled=!current.artifactAvailable;}}
select.addEventListener('change',show);find('previous').onclick=()=>{select.selectedIndex=Math.max(0,select.selectedIndex-1);show();};find('next').onclick=()=>{select.selectedIndex=Math.min(select.options.length-1,select.selectedIndex+1);show();};find('open').onclick=()=>void activate();find('reload').onclick=()=>void activate(true);find('narrow').onclick=()=>{frame.style.width='390px';frame.style.maxWidth='100%';};find('wide').onclick=()=>{frame.style.width='100%';};find('export').onclick=()=>{save();try{const result=validateReviewExport(draft,packet),url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`${packet.participant}-travel-review.json`;link.click();URL.revokeObjectURL(url);status.textContent='Your ratings were exported locally.';}catch(error){status.textContent=error.message;}};
show();
