import { useId } from 'react'
import { DatasetIdSchema, TransportModeSchema, type TransportMode } from '../../contracts'
import { useArtifact, useTravelAction, useTravelQuery, filterPredicate, carrierLabel, cityLabel, legKey } from '../context'
import type { WidgetProps } from '../layout'
export function Control({kind,...props}:WidgetProps & {kind:string}) {
  const {state,services}=useArtifact(props.artifactRef); const dispatch=useTravelAction(props.artifactRef); const id=useId()
  const patch=(filters:typeof state.filters)=>dispatch({kind:'filters',artifactId:state.artifactId,filters})
  const label=props.title ?? ({PriceRange:'Maximum fare',DurationRange:'Maximum journey time',DirectToggle:'Direct connections only',DateStrip:'Departure date',DateWindow:'Departure date',SortSelect:'Sort options',CarrierFilter:'Carriers',StayAllocation:'Nights in each city',ModeChips:'Transport modes'}[kind] ?? kind)
  const modeLeg=props.datasetRef?legKey(services.bridge.getManifest(DatasetIdSchema.parse(props.datasetRef)).coverage):undefined;const modes=modeLeg?(state.modesByLeg[modeLeg]??state.filters.modes):state.filters.modes
  if(kind==='ModeChips') return <fieldset className="travel-fieldset"><legend>{label}</legend><div className="travel-chips">{TransportModeSchema.options.map((mode:TransportMode)=><button key={mode} type="button" aria-pressed={modes.includes(mode)} onClick={()=>{const next=modes.includes(mode)?modes.filter(m=>m!==mode):[...modes,mode];if(modeLeg)dispatch({kind:'modesByLeg',artifactId:state.artifactId,modesByLeg:{...state.modesByLeg,[modeLeg]:next}});else patch({...state.filters,modes:next})}}>{cityLabel(mode)}</button>)}</div><small>No modes selected means all modes.</small></fieldset>
  if(kind==='DirectToggle') return <label className="travel-check"><input type="checkbox" checked={state.filters.directOnly} onChange={e=>patch({...state.filters,directOnly:e.target.checked})}/>{label}</label>
  if(kind==='SortSelect') return <label className="travel-field" htmlFor={id}>{label}<select id={id} value={`${state.sort.field}:${state.sort.direction}`} onChange={e=>{const [field,direction]=e.target.value.split(':');if((field==='priceCents'||field==='durationMinutes'||field==='departureMinutes')&&(direction==='asc'||direction==='desc'))dispatch({kind:'sort',artifactId:state.artifactId,sort:{field,direction}})}}><option value="priceCents:asc">Lowest price</option><option value="priceCents:desc">Highest price</option><option value="durationMinutes:asc">Fastest first</option><option value="durationMinutes:desc">Longest first</option><option value="departureMinutes:asc">Earliest first</option></select></label>
  if(kind==='DateStrip') return <label className="travel-field" htmlFor={id}>{label}<input id={id} type="date" value={state.dates.start} onChange={e=>{if(e.target.value)dispatch({kind:'dates',artifactId:state.artifactId,dates:{start:e.target.value}})}}/></label>
  if(kind==='DateWindow') return <fieldset className="travel-fieldset"><legend>{props.title??'Departure window'}</legend><label className="travel-field" htmlFor={`${id}-start`}>Window starts<input id={`${id}-start`} type="date" value={state.dates.start} onChange={e=>{const start=e.target.value;if(start)dispatch({kind:'dates',artifactId:state.artifactId,dates:{start,end:state.dates.end&&state.dates.end>=start?state.dates.end:start}})}}/></label><label className="travel-field" htmlFor={`${id}-end`}>Window ends<input id={`${id}-end`} type="date" min={state.dates.start} value={state.dates.end??state.dates.start} onChange={e=>{const end=e.target.value;if(end&&end>=state.dates.start)dispatch({kind:'dates',artifactId:state.artifactId,dates:{start:state.dates.start,end}})}}/></label><small>Includes both dates. Fares outside loaded coverage are requested locally.</small></fieldset>
  if(kind==='PriceRange'||kind==='DurationRange') { const price=kind==='PriceRange'; const value=price?state.filters.maxPriceCents:state.filters.maxDurationMinutes;return <label className="travel-field" htmlFor={id}>{label}<input id={id} type="number" min={price?0:1} step={price?1:15} placeholder="No limit" value={value===undefined?'':price?value/100:value} onChange={e=>{const value=e.target.value===''?undefined:price?Math.round(Number(e.target.value)*100):Number(e.target.value);if(value!==undefined&&(!Number.isFinite(value)||!Number.isInteger(value)||value<(price?0:1)))return;patch(price?{...state.filters,maxPriceCents:value}:{...state.filters,maxDurationMinutes:value})}}/><small>{price?'EUR per passenger, synthetic':'Minutes'}</small></label> }
  if(kind==='StayAllocation') return <fieldset className="travel-fieldset"><legend>{label}</legend>{state.stays.length?state.stays.map((stay,i)=><label className="travel-field" key={`${stay.cityId}-${i}`}>{cityLabel(stay.cityId)}<input type="number" min="0" max="30" value={stay.nights} onChange={e=>{const nights=Number(e.target.value);if(Number.isInteger(nights)&&nights>=0&&nights<=30)dispatch({kind:'stays',artifactId:state.artifactId,stays:state.stays.map((s,j)=>j===i?{...s,nights}:s)})}}/></label>):<p>Add stops in your next message to allocate stays.</p>}</fieldset>
  if(kind==='CarrierFilter')return <CarrierControl {...props}/>
  return null
}
function CarrierControl(props:WidgetProps) {
  const result=useTravelQuery(props.artifactRef,props.datasetRef,(state,id)=>({version:1,sources:[{datasetRef:id,alias:'f'}],where:filterPredicate({...state,filters:{...state.filters,carrierIds:[]}}),groupBy:['carrierId'],metrics:[{as:'count',op:'count'}],limit:30}));const dispatch=useTravelAction(props.artifactRef)
  return <fieldset className="travel-fieldset"><legend>{props.title??'Carriers'}</legend>{result.data?.rows.map(row=>typeof row.carrierId==='string'?<label className="travel-check" key={row.carrierId}><input type="checkbox" checked={result.state.filters.carrierIds.includes(row.carrierId)} onChange={e=>{if(typeof row.carrierId==='string')dispatch({kind:'filters',artifactId:result.state.artifactId,filters:{...result.state.filters,carrierIds:e.target.checked?[...result.state.filters.carrierIds,row.carrierId]:result.state.filters.carrierIds.filter(c=>c!==row.carrierId)}})}}/>{carrierLabel({carrierId:row.carrierId},result.services.bridge,result.datasetId)}</label>:null)}</fieldset>
}
