import { useId } from 'react'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { FieldLegend, FieldSet } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select'
import { RequestNotice } from '../status/request-notice'
import { DatasetIdSchema, TransportModeSchema, type TransportMode } from '../../contracts'
import { useArtifact, useCarrierFacets, useTravelAction, carrierLabel, cityLabel } from '../context'
import type { WidgetProps } from '../layout'
import type { InputField } from '../../contracts/display-context'
import { recordDisplayInteraction, useDisplayNode, usePublishDisplay } from '../display-context-provider'
import { useProjectionDisplay } from '../display-records'
export function Control({kind,...props}:WidgetProps & {kind:string}) {
  const {state,services}=useArtifact(props.artifactRef); const dispatch=useTravelAction(props.artifactRef); const id=useId();const display=useDisplayNode()
  const act=(command:Parameters<typeof dispatch>[0],fields:readonly InputField[])=>{recordDisplayInteraction(display.store,{artifactId:props.artifactRef,componentRef:display.componentRef,action:command.kind==='select'?(command.selected?'select':'deselect'):'input',inputFields:fields});return dispatch(command)}
  const patch=(filters:typeof state.filters,fields:readonly InputField[])=>act({kind:'filters',artifactId:state.artifactId,filters},fields)
  const label=props.title ?? ({PriceRange:'Maximum fare',DurationRange:'Maximum journey time',DirectToggle:'Direct connections only',DateStrip:'Departure date',DateWindow:'Departure date',SortSelect:'Sort options',CarrierFilter:'Carriers',StayAllocation:'Nights in each city',ModeChips:'Transport modes'}[kind] ?? kind)
  const parsedDataset=props.datasetRef?DatasetIdSchema.safeParse(props.datasetRef):undefined
  const binding=parsedDataset?.success?services.bridge.findBinding(parsedDataset.data):undefined,modeLeg=binding?`${binding.manifest.coverage.originId}:${binding.manifest.coverage.destinationId}`:undefined;const modes=modeLeg?(state.modesByLeg[modeLeg]??state.filters.modes):state.filters.modes
  const inputFields:InputField[]=kind==='ModeChips'?['modes']:kind==='CarrierFilter'?['carrierIds']:kind==='PriceRange'?['maxPriceCents']:kind==='DurationRange'?['maxDurationMinutes']:kind==='DirectToggle'?['directOnly']:kind==='SortSelect'?['sort']:kind==='StayAllocation'?['stayNights']:['dateWindow']
  usePublishDisplay({inputs:{dateWindow:{from:state.dates.start,to:state.dates.end??state.dates.start},modes,carrierIds:state.filters.carrierIds,minPriceCents:state.filters.minPriceCents,maxPriceCents:state.filters.maxPriceCents,maxDurationMinutes:state.filters.maxDurationMinutes,directOnly:state.filters.directOnly,sort:state.sort},provenance:display.store?.provenance(props.artifactRef,inputFields),display:{payload:{kind:'status',label},totalDisplayed:1,includedCount:1,complete:true,omittedCount:0},publishDisplay:kind!=='CarrierFilter'})
  if(kind==='ModeChips') return <FieldSet className="travel-fieldset"><FieldLegend>{label}</FieldLegend><div className="travel-chips">{TransportModeSchema.options.map((mode:TransportMode)=><Button key={mode} variant="outline" type="button" aria-pressed={modes.includes(mode)} onClick={()=>{const next=modes.includes(mode)?modes.filter(m=>m!==mode):[...modes,mode];if(modeLeg)act({kind:'modesByLeg',artifactId:state.artifactId,modesByLeg:{...state.modesByLeg,[modeLeg]:next}},['modes']);else patch({...state.filters,modes:next},['modes'])}}>{cityLabel(mode)}</Button>)}</div><small>No modes selected means all modes.</small></FieldSet>
  if(kind==='DirectToggle') return <Label className="travel-check"><Checkbox checked={state.filters.directOnly} onCheckedChange={checked=>patch({...state.filters,directOnly:checked===true},['directOnly'])}/>{label}</Label>
  if(kind==='SortSelect') return <Label className="travel-field" htmlFor={id}>{label}<NativeSelect id={id} value={`${state.sort.field}:${state.sort.direction}`} onChange={e=>{const [field,direction]=e.target.value.split(':');if((field==='priceCents'||field==='durationMinutes'||field==='departureMinutes')&&(direction==='asc'||direction==='desc'))act({kind:'sort',artifactId:state.artifactId,sort:{field,direction}},['sort'])}}><NativeSelectOption value="priceCents:asc">Lowest price</NativeSelectOption><NativeSelectOption value="priceCents:desc">Highest price</NativeSelectOption><NativeSelectOption value="durationMinutes:asc">Fastest first</NativeSelectOption><NativeSelectOption value="durationMinutes:desc">Longest first</NativeSelectOption><NativeSelectOption value="departureMinutes:asc">Earliest first</NativeSelectOption></NativeSelect></Label>
  if(kind==='DateStrip') return <Label className="travel-field" htmlFor={id}>{label}<Input id={id} type="date" value={state.dates.start} onChange={e=>{if(e.target.value)act({kind:'dates',artifactId:state.artifactId,dates:{start:e.target.value}},['dateWindow'])}}/></Label>
  if(kind==='DateWindow') return <FieldSet className="travel-fieldset"><FieldLegend>{props.title??'Departure window'}</FieldLegend><Label className="travel-field" htmlFor={`${id}-start`}>Window starts<Input id={`${id}-start`} type="date" value={state.dates.start} onChange={e=>{const start=e.target.value;if(start)act({kind:'dates',artifactId:state.artifactId,dates:{start,end:state.dates.end&&state.dates.end>=start?state.dates.end:start}},['dateWindow'])}}/></Label><Label className="travel-field" htmlFor={`${id}-end`}>Window ends<Input id={`${id}-end`} type="date" min={state.dates.start} value={state.dates.end??state.dates.start} onChange={e=>{const end=e.target.value;if(end&&end>=state.dates.start)act({kind:'dates',artifactId:state.artifactId,dates:{start:state.dates.start,end}},['dateWindow'])}}/></Label><small>Includes both dates. Fares outside loaded coverage are requested locally.</small></FieldSet>
  if(kind==='PriceRange'||kind==='DurationRange') { const price=kind==='PriceRange'; const value=price?state.filters.maxPriceCents:state.filters.maxDurationMinutes;return <Label className="travel-field" htmlFor={id}>{label}<Input id={id} type="number" min={price?0:1} step={price?1:15} placeholder="No limit" value={value===undefined?'':price?value/100:value} onChange={e=>{const value=e.target.value===''?undefined:price?Math.round(Number(e.target.value)*100):Number(e.target.value);if(value!==undefined&&(!Number.isFinite(value)||!Number.isInteger(value)||value<(price?0:1)))return;patch(price?{...state.filters,maxPriceCents:value}:{...state.filters,maxDurationMinutes:value},[price?'maxPriceCents':'maxDurationMinutes'])}}/><small>{price?'EUR per passenger, synthetic':'Minutes'}</small></Label> }
  if(kind==='StayAllocation') return <FieldSet className="travel-fieldset"><FieldLegend>{label}</FieldLegend>{state.stays.length?state.stays.map((stay,i)=><Label className="travel-field" key={`${stay.cityId}-${i}`}>{cityLabel(stay.cityId)}<Input type="number" min="0" max="30" value={stay.nights} onChange={e=>{const nights=Number(e.target.value);if(Number.isInteger(nights)&&nights>=0&&nights<=30)act({kind:'stays',artifactId:state.artifactId,stays:state.stays.map((s,j)=>j===i?{...s,nights}:s)},['stayNights'])}}/></Label>):<p role="status">Add stops in your next message to allocate stays.</p>}</FieldSet>
  if(kind==='CarrierFilter')return <CarrierControl {...props}/>
  return null
}
function CarrierControl(props:WidgetProps) {
  const node=useDisplayNode(),{state,services}=useArtifact(props.artifactRef),dispatch=useTravelAction(props.artifactRef),result=useCarrierFacets(props.artifactRef,{componentRef:node.componentRef??`${props.artifactRef}:carrier-facets`,purpose:'carrier-facets',datasetRef:props.datasetRef}),options=result.data?.options??[],cells=options.map(option=>({key:option.carrierId,label:option.carrierName??option.carrierId,value:option.count,unit:'count' as const}))
  useProjectionDisplay(result,{payload:{kind:'aggregate',cells},totalDisplayed:cells.length,includedCount:cells.length,complete:true,omittedCount:0});const status=result.data?'ready':result.queryState.status==='error'?'error':'loading',resourceKey=result.queryState.status==='ready'||result.queryState.status==='refreshing'?result.queryState.current.resourceKey:result.queryState.status==='error'?result.queryState.previous?.resourceKey:undefined
  return <FieldSet className="travel-fieldset"><FieldLegend>{props.title??'Carriers'}</FieldLegend><RequestNotice status={status} label="Carriers" empty={!options.length}/>{options.map(option=><Label className="travel-check" key={option.carrierId}><Checkbox checked={state.filters.carrierIds.includes(option.carrierId)} onCheckedChange={checked=>{recordDisplayInteraction(node.store,{artifactId:props.artifactRef,componentRef:node.componentRef,action:'input',inputFields:['carrierIds']});dispatch({kind:'filters',artifactId:state.artifactId,filters:{...state.filters,carrierIds:checked===true?[...state.filters.carrierIds,option.carrierId]:state.filters.carrierIds.filter(carrierId=>carrierId!==option.carrierId)}})}}/>{carrierLabel(option,services.bridge,resourceKey)} · {option.count}</Label>)}</FieldSet>
}
