import { useId } from 'react'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { FieldLegend, FieldSet } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select'
import { RequestNotice } from '../status/request-notice'
import { DatasetIdSchema, TransportModeSchema, type TransportMode } from '../../contracts'
import { useArtifact, useTravelAction, useTravelQuery, filterPredicate, carrierLabel, cityLabel, legKey } from '../context'
import type { WidgetProps } from '../layout'
export function Control({kind,...props}:WidgetProps & {kind:string}) {
  const {state,services}=useArtifact(props.artifactRef); const dispatch=useTravelAction(props.artifactRef); const id=useId()
  const patch=(filters:typeof state.filters)=>dispatch({kind:'filters',artifactId:state.artifactId,filters})
  const label=props.title ?? ({PriceRange:'Maximum fare',DurationRange:'Maximum journey time',DirectToggle:'Direct connections only',DateStrip:'Departure date',DateWindow:'Departure date',SortSelect:'Sort options',CarrierFilter:'Carriers',StayAllocation:'Nights in each city',ModeChips:'Transport modes'}[kind] ?? kind)
  const modeLeg=props.datasetRef?legKey(services.bridge.getManifest(DatasetIdSchema.parse(props.datasetRef)).coverage):undefined;const modes=modeLeg?(state.modesByLeg[modeLeg]??state.filters.modes):state.filters.modes
  if(kind==='ModeChips') return <FieldSet className="travel-fieldset"><FieldLegend>{label}</FieldLegend><div className="travel-chips">{TransportModeSchema.options.map((mode:TransportMode)=><Button key={mode} variant="outline" type="button" aria-pressed={modes.includes(mode)} onClick={()=>{const next=modes.includes(mode)?modes.filter(m=>m!==mode):[...modes,mode];if(modeLeg)dispatch({kind:'modesByLeg',artifactId:state.artifactId,modesByLeg:{...state.modesByLeg,[modeLeg]:next}});else patch({...state.filters,modes:next})}}>{cityLabel(mode)}</Button>)}</div><small>No modes selected means all modes.</small></FieldSet>
  if(kind==='DirectToggle') return <Label className="travel-check"><Checkbox checked={state.filters.directOnly} onCheckedChange={checked=>patch({...state.filters,directOnly:checked===true})}/>{label}</Label>
  if(kind==='SortSelect') return <Label className="travel-field" htmlFor={id}>{label}<NativeSelect id={id} value={`${state.sort.field}:${state.sort.direction}`} onChange={e=>{const [field,direction]=e.target.value.split(':');if((field==='priceCents'||field==='durationMinutes'||field==='departureMinutes')&&(direction==='asc'||direction==='desc'))dispatch({kind:'sort',artifactId:state.artifactId,sort:{field,direction}})}}><NativeSelectOption value="priceCents:asc">Lowest price</NativeSelectOption><NativeSelectOption value="priceCents:desc">Highest price</NativeSelectOption><NativeSelectOption value="durationMinutes:asc">Fastest first</NativeSelectOption><NativeSelectOption value="durationMinutes:desc">Longest first</NativeSelectOption><NativeSelectOption value="departureMinutes:asc">Earliest first</NativeSelectOption></NativeSelect></Label>
  if(kind==='DateStrip') return <Label className="travel-field" htmlFor={id}>{label}<Input id={id} type="date" value={state.dates.start} onChange={e=>{if(e.target.value)dispatch({kind:'dates',artifactId:state.artifactId,dates:{start:e.target.value}})}}/></Label>
  if(kind==='DateWindow') return <FieldSet className="travel-fieldset"><FieldLegend>{props.title??'Departure window'}</FieldLegend><Label className="travel-field" htmlFor={`${id}-start`}>Window starts<Input id={`${id}-start`} type="date" value={state.dates.start} onChange={e=>{const start=e.target.value;if(start)dispatch({kind:'dates',artifactId:state.artifactId,dates:{start,end:state.dates.end&&state.dates.end>=start?state.dates.end:start}})}}/></Label><Label className="travel-field" htmlFor={`${id}-end`}>Window ends<Input id={`${id}-end`} type="date" min={state.dates.start} value={state.dates.end??state.dates.start} onChange={e=>{const end=e.target.value;if(end&&end>=state.dates.start)dispatch({kind:'dates',artifactId:state.artifactId,dates:{start:state.dates.start,end}})}}/></Label><small>Includes both dates. Fares outside loaded coverage are requested locally.</small></FieldSet>
  if(kind==='PriceRange'||kind==='DurationRange') { const price=kind==='PriceRange'; const value=price?state.filters.maxPriceCents:state.filters.maxDurationMinutes;return <Label className="travel-field" htmlFor={id}>{label}<Input id={id} type="number" min={price?0:1} step={price?1:15} placeholder="No limit" value={value===undefined?'':price?value/100:value} onChange={e=>{const value=e.target.value===''?undefined:price?Math.round(Number(e.target.value)*100):Number(e.target.value);if(value!==undefined&&(!Number.isFinite(value)||!Number.isInteger(value)||value<(price?0:1)))return;patch(price?{...state.filters,maxPriceCents:value}:{...state.filters,maxDurationMinutes:value})}}/><small>{price?'EUR per passenger, synthetic':'Minutes'}</small></Label> }
  if(kind==='StayAllocation') return <FieldSet className="travel-fieldset"><FieldLegend>{label}</FieldLegend>{state.stays.length?state.stays.map((stay,i)=><Label className="travel-field" key={`${stay.cityId}-${i}`}>{cityLabel(stay.cityId)}<Input type="number" min="0" max="30" value={stay.nights} onChange={e=>{const nights=Number(e.target.value);if(Number.isInteger(nights)&&nights>=0&&nights<=30)dispatch({kind:'stays',artifactId:state.artifactId,stays:state.stays.map((s,j)=>j===i?{...s,nights}:s)})}}/></Label>):<p role="status">Add stops in your next message to allocate stays.</p>}</FieldSet>
  if(kind==='CarrierFilter')return <CarrierControl {...props}/>
  return null
}
function CarrierControl(props:WidgetProps) {
  const result=useTravelQuery(props.artifactRef,props.datasetRef,(state,id)=>({version:1,sources:[{datasetRef:id,alias:'f'}],where:filterPredicate({...state,filters:{...state.filters,carrierIds:[]}}),groupBy:['carrierId'],metrics:[{as:'count',op:'count'}],limit:30}));const dispatch=useTravelAction(props.artifactRef)
  return <FieldSet className="travel-fieldset"><FieldLegend>{props.title??'Carriers'}</FieldLegend><RequestNotice status={result.status} label="Carriers" empty={!result.data?.rows.length}/>{result.data?.rows.map(row=>typeof row.carrierId==='string'?<Label className="travel-check" key={row.carrierId}><Checkbox checked={result.state.filters.carrierIds.includes(row.carrierId)} onCheckedChange={checked=>{if(typeof row.carrierId==='string')dispatch({kind:'filters',artifactId:result.state.artifactId,filters:{...result.state.filters,carrierIds:checked===true?[...result.state.filters.carrierIds,row.carrierId]:result.state.filters.carrierIds.filter(c=>c!==row.carrierId)}})}}/>{carrierLabel({carrierId:row.carrierId},result.services.bridge,result.datasetId)}</Label>:null)}</FieldSet>
}
