import assert from 'node:assert/strict'
import { PersistedThreadSchema } from '../../src/generative/state/persistence'
import { chromium } from '@playwright/test'
import { CoverageRequestSchema } from '../../src/generative/contracts'
import { coverageKey,stableRef } from '../../src/generative/data/resource-loader'
const requests=[{originIds:['london'],destinationIds:['paris'],dateWindow:{from:'2026-10-09',to:'2026-10-15'},modes:['train','bus','flight','ferry'],passengers:2},{originIds:['paris'],destinationIds:['barcelona'],dateWindow:{from:'2026-10-11',to:'2026-10-17'},modes:['train','bus','flight','ferry'],passengers:2}].map(value=>CoverageRequestSchema.parse(value))
const refs=requests.map(request=>`dataset-${stableRef(coverageKey(request))}`)
const node=(name:string,key:string,extra:object={})=>({$type:name,$key:key,artifactRef:'smoke-artifact',...extra})
const scene=node('TravelSurface','root',{children:[node('RouteMap','route'),node('DateStrip','date'),node('StayAllocation','stays'),node('Inline','modes',{children:[node('ModeChips','mode-1',{datasetRef:refs[0],title:'London to Paris modes'}),node('ModeChips','mode-2',{datasetRef:refs[1],title:'Paris to Barcelona modes'})]}),node('ResponsiveGrid','choices',{children:[node('FareCards','fare-1',{datasetRef:refs[0],title:'First leg choices'}),node('FareCards','fare-2',{datasetRef:refs[1],title:'Second leg choices'})]}),node('SelectedItinerary','selected'),node('SyntheticTotal','total')]})
const state={artifactId:'smoke-artifact',revision:0,runtimeVariables:{},datasetRefs:refs,filters:{modes:[],carrierIds:[],directOnly:false},dates:{start:'2026-10-09'},stays:[{cityId:'paris',nights:2},{cityId:'barcelona',nights:4}],modesByLeg:{},sort:{field:'priceCents',direction:'asc'},selectedFareIds:[],pending:[],lastInteractionAt:new Date().toISOString()}
const record={schemaVersion:'1.0.0',catalogVersion:'1.0.0',activeArtifactId:'smoke-artifact',parserVersion:'native-present-1',queryVersion:'1',artifacts:[{source:JSON.stringify(scene),state}],descriptors:refs.map((datasetId,index)=>({datasetId,request:requests[index],sourceVersion:'sqlite-demo-v1',complete:true})),messages:[{id:'smoke-user',role:'user',parts:[{type:'text',text:'Local multi-city verification fixture'}]},{id:'smoke-scene',role:'assistant',parts:[{type:'tool-present',toolCallId:'smoke-present',state:'output-available',input:scene,output:{}}]},{id:'smoke-done',role:'assistant',parts:[{type:'text',text:'Local fixture ready.'}]}]}
const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1280,height:1000}});const page=await context.newPage();const errors:string[]=[];let chatRequests=0;page.on('pageerror',error=>errors.push(error.message));await page.route('**/api/chat',route=>{chatRequests++;return route.abort()})
try{
 await page.goto(`${process.env.OMIO_DEMO_URL??'http://127.0.0.1:5173'}/generative`);await page.evaluate(async record=>{await new Promise<void>((resolve,reject)=>{const request=indexedDB.open('omio-generative-state',1);request.onupgradeneeded=()=>request.result.createObjectStore('threads');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const tx=request.result.transaction('threads','readwrite');tx.objectStore('threads').put(record,'travel-proof');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)}})},record);await page.reload()
 const first=page.locator('section.travel-panel').filter({has:page.getByRole('heading',{name:'First leg choices',exact:true})});const second=page.locator('section.travel-panel').filter({has:page.getByRole('heading',{name:'Second leg choices',exact:true})});await first.getByRole('button',{name:/^Select /}).first().waitFor({timeout:60000});await second.getByRole('button',{name:/^Select /}).first().waitFor({timeout:60000})
 assert.ok((await first.textContent())?.includes('2026-10-09'));assert.ok((await second.textContent())?.includes('2026-10-11'))
 await first.getByRole('button',{name:/^Select /}).first().click();await second.getByRole('button',{name:/^Select /}).first().click();const itinerary=page.locator('section[aria-label="Selected itinerary"] li');await itinerary.nth(1).waitFor();await page.getByText('2 passengers',{exact:true}).first().waitFor();assert.equal(await itinerary.count(),2)
 await first.locator('button[aria-pressed="false"]').first().click();await first.locator('button[aria-pressed="true"]').first().waitFor();assert.equal(await first.locator('button[aria-pressed="true"]').count(),1);assert.equal(await second.locator('button[aria-pressed="true"]').count(),1);assert.equal(await itinerary.count(),2)
 await page.getByRole('spinbutton',{name:'Paris',exact:true}).fill('3');await page.getByRole('spinbutton',{name:'Paris',exact:true}).press('Tab');await page.waitForFunction(()=>Array.from(document.querySelectorAll('section')).some(section=>section.querySelector('h3')?.textContent==='Second leg choices'&&section.textContent?.includes('2026-10-12')))
 await page.getByLabel('Departure date',{exact:true}).fill('2026-10-20');await page.getByLabel('Departure date',{exact:true}).press('Tab');await page.waitForFunction(()=>{const sections=Array.from(document.querySelectorAll('section'));return sections.some(section=>section.querySelector('h3')?.textContent==='First leg choices'&&section.textContent?.includes('2026-10-20'))&&sections.some(section=>section.querySelector('h3')?.textContent==='Second leg choices'&&section.textContent?.includes('2026-10-23'))},{timeout:60000})
 await page.waitForTimeout(120);assert.equal(chatRequests,0);assert.equal(errors.length,0);assert.equal(await page.getByRole('alert').count(),0)
 const saved=PersistedThreadSchema.parse(await page.evaluate(()=>new Promise(resolve=>{const request=indexedDB.open('omio-generative-state',1);request.onsuccess=()=>{const read=request.result.transaction('threads').objectStore('threads').get('travel-proof');read.onsuccess=()=>resolve(read.result)}})));assert.equal(saved.artifacts[0].state.selectedFareIds.length,0);assert.equal(saved.artifacts[0].state.stays[0].nights,3);assert.equal(saved.artifacts[0].state.dates.start,'2026-10-20');assert.ok(saved.artifacts[0].state.datasetRefs.length>=4)
 console.log(JSON.stringify({status:'pass',kind:'actual-local-fare-browser-smoke',modelRequests:chatRequests,initialDates:['2026-10-09','2026-10-11'],afterStayDate:'2026-10-12',outsideDates:['2026-10-20','2026-10-23'],sameLegReplacement:true,invalidSelectionsCleared:true,seedRefsRetained:refs.every(ref=>saved.artifacts[0].state.datasetRefs.includes(ref)),resourceHandles:saved.artifacts[0].state.datasetRefs.length,pageErrors:errors}))
}finally{await browser.close()}
