import { expect,it } from 'vitest'
import { acceptTurn,spendTool,recordScene,getAcceptedScenes,getRequiredScene } from './turn-budget'
import { CODEX_DEVELOPER_INSTRUCTIONS } from './codex-provider'
import { ArtifactIdSchema,UIStateRevisionSchema } from '../src/generative/contracts'
import { createUIStateStore } from '../src/generative/state/ui-state-store'
import { createFareDataBridge } from '../src/generative/data/fare-data-bridge'
import { exportAgentContext } from '../src/generative/state/snapshot-exporter'
import { createDisplayContextStore } from '../src/generative/state/display-context'
import type { ChatRequest } from './request-schema'
const artifact=ArtifactIdSchema.parse('completion-artifact'),other=ArtifactIdSchema.parse('other-artifact')
function request():ChatRequest{const store=createUIStateStore();store.initializeMissing(artifact,{});store.initializeMissing(other,{});return{id:crypto.randomUUID(),currentContext:exportAgentContext({turnId:'completion',activeArtifactId:artifact,artifactIds:[artifact,other],store,bridge:createFareDataBridge(),displayStore:createDisplayContextStore()}),messages:[{id:'user',role:'user',parts:[{type:'text',text:'Compose both views.'}]}]}}
function ack(input:ChatRequest){const key=acceptTurn(input);spendTool(key,'present');recordScene(key,'scene','present',artifact,UIStateRevisionSchema.parse(0));input.messages.push({id:'assistant',role:'assistant',parts:[{type:'tool-present',toolCallId:'scene',state:'output-available',input:{artifactRef:artifact},output:{}}]});return key}
function activeScene(input:ChatRequest,revision=1){const current=input.currentContext.artifacts.find(candidate=>candidate.artifactId===artifact);if(!current)throw new Error('Missing artifact');current.revision=UIStateRevisionSchema.parse(revision);current.componentBindings=[{key:'comparison',type:'ComparisonTable'}]}
function edit(input:ChatRequest,options:{kind?:'route'|'dates'|'sort'|'select';artifactRef?:typeof artifact;status?:'applied'|'stale';revision?:number}={}){const kind=options.kind??'route',artifactRef=options.artifactRef??artifact,command=kind==='route'?{kind,citySequence:['london','paris']}:kind==='dates'?{kind,dates:{start:'2026-10-26'}}:kind==='sort'?{kind,sort:{field:'priceCents',direction:'asc'}}:{kind,selected:false,fareId:'fare-1'};input.messages.push({id:`assistant-${crypto.randomUUID()}`,role:'assistant',parts:[{type:'tool-edit_artifact',toolCallId:`edit-${crypto.randomUUID()}`,state:'output-available',input:{artifactRef,expectedRevision:0,commands:[command]},output:{artifactId:artifactRef,revision:options.revision??1,status:options.status??'applied'}}]})}
it('none finalizes fulfilled tool-backed requests, not only text-only requests',()=>{expect(CODEX_DEVELOPER_INSTRUCTIONS).toContain('fulfilled tool-backed');expect(CODEX_DEVELOPER_INSTRUCTIONS).toContain('different requested artifact');expect(CODEX_DEVELOPER_INSTRUCTIONS).toContain('new UI revision')})
it('reports current-turn accepted scenes at the captured UI revision',()=>{const input=request(),key=ack(input);expect(getAcceptedScenes(key,input)).toEqual([{artifactRef:artifact,uiStateRevision:0,toolName:'present'}]);expect(getAcceptedScenes(key,input).some(scene=>scene.artifactRef===other)).toBe(false)})
it('does not finalize a new user turn, changed UI revision, explicit regenerate or real error',()=>{const input=request(),key=ack(input);input.currentContext.artifacts[0]!.revision=UIStateRevisionSchema.parse(1);expect(getAcceptedScenes(key,input)).toEqual([]);input.currentContext.artifacts[0]!.revision=UIStateRevisionSchema.parse(0);input.trigger='regenerate-message';expect(getAcceptedScenes(key,input)).toEqual([]);delete input.trigger;input.messages.at(-1)!.parts[0]!.output={artifactId:artifact,programRevision:0,status:'error'};expect(getAcceptedScenes(key,input)).toEqual([]);input.messages.push({id:'next-user',role:'user',parts:[{type:'text',text:'Compose again.'}]});expect(getAcceptedScenes(acceptTurn(input),input)).toEqual([])})
it.each(['route','dates'] as const)('requires a current presentation after an applied active %s edit',kind=>{const input=request();activeScene(input);edit(input,{kind});expect(getRequiredScene(input,[])).toEqual({artifactRef:artifact,uiStateRevision:1,reason:'scope-edit'})})
it('clears the scope-edit obligation after a current-revision presentation',()=>{const input=request();activeScene(input);edit(input);const key=acceptTurn(input);spendTool(key,'present');recordScene(key,'current-scene','present',artifact,UIStateRevisionSchema.parse(1));input.messages.push({id:'presented',role:'assistant',parts:[{type:'tool-present',toolCallId:'current-scene',state:'output-available',input:{artifactRef:artifact},output:{}}]});const accepted=getAcceptedScenes(key,input);expect(accepted).toEqual([{artifactRef:artifact,uiStateRevision:1,toolName:'present'}]);expect(getRequiredScene(input,accepted)).toBeUndefined()})
it('leaves first composition and harmless or irrelevant edits free to finish with text',()=>{const untouched=request();activeScene(untouched);expect(getRequiredScene(untouched,[])).toBeUndefined();for(const options of [{kind:'sort' as const},{kind:'select' as const},{status:'stale' as const},{revision:0},{artifactRef:other}]){const input=request();activeScene(input);edit(input,options);expect(getRequiredScene(input,[])).toBeUndefined()}const noScene=request();edit(noScene);expect(getRequiredScene(noScene,[])).toBeUndefined();const laterQuestion=request();activeScene(laterQuestion);edit(laterQuestion);laterQuestion.messages.push({id:'later-user',role:'user',parts:[{type:'text',text:'Explain that view.'}]});expect(getRequiredScene(laterQuestion,[])).toBeUndefined()})
