import type { ComponentDescriptor } from '../contracts';
const refs = [
  {name:'artifactRef',kind:'ref',required:true}, {name:'datasetRef',kind:'ref',required:false},
  {name:'actionRef',kind:'ref',required:false}, {name:'selectorRef',kind:'ref',required:false},
  {name:'title',kind:'text',required:false}, {name:'variant',kind:'variant',required:false}, {name:'body',kind:'text',required:false},
] satisfies ComponentDescriptor['props'];
const descriptor = (name: string, group: ComponentDescriptor['group'], description: string, children = false): ComponentDescriptor => ({ name, group, description, props: refs, children });
export const descriptors: ReadonlyArray<ComponentDescriptor> = [
  descriptor('TravelHero','layout','Travel artifact headline and introduction',true),
  descriptor('Carousel','layout','Accessible horizontal panels',true),
  descriptor('DateWindow','control','Bounded local date window'),
  descriptor('FarePicker','control','Direct local fare selection'),
  descriptor('CheapestFastest','view','Local cheapest and fastest comparison'),
  descriptor('TravelSurface','layout','Root travel artifact with subscribed local state',true),
  descriptor('Section','layout','Named story section',true),
  descriptor('Stack','layout','Vertical arrangement',true),
  descriptor('Inline','layout','Horizontal wrapping arrangement',true),
  descriptor('ResponsiveGrid','layout','Responsive equal-column arrangement',true),
  descriptor('SplitPane','layout','Responsive primary and supporting sections',true),
  descriptor('StickySummary','layout','Persistent selected-trip summary',true),
  descriptor('Tabs','layout','Accessible tabbed sections',true),
  descriptor('Callout','layout','Short heading and explanatory body text up to600 characters',true),
  descriptor('DateStrip','control','Direct local date selection'),
  descriptor('ModeChips','control','Direct local transport mode filtering'),
  descriptor('CarrierFilter','control','Direct local carrier selection'),
  descriptor('PriceRange','control','Direct local price limit'),
  descriptor('DurationRange','control','Direct local duration limit'),
  descriptor('DirectToggle','control','Direct-only local filter'),
  descriptor('SortSelect','control','Price duration or departure sorting'),
  descriptor('StayAllocation','control','Multi-city stay nights allocation'),
  descriptor('FareCards','view','Locally resolved fare choices'),
  descriptor('ComparisonTable','view','Locally resolved ranked fare comparison'),
  descriptor('ComparisonMatrix','view','Locally grouped mode comparison'),
  descriptor('PriceCalendar','view','Locally grouped price-by-day view'),
  descriptor('ModeBreakdown','view','Locally grouped transport totals'),
  descriptor('SyntheticTotal','view','Selected synthetic per-passenger EUR total'),
  descriptor('CoverageSummary','view','Resource completeness and bounds'),
  descriptor('CitySequence','view','Ordered stops and adjacent legs'),
  descriptor('RouteMap','view','Schematic local route visualization'),
  descriptor('ItineraryTimeline','view','Selected adjacent-leg chronology'),
  descriptor('DurationPricePlot','view','Local duration and price comparison'),
  descriptor('SelectedItinerary','view','Selected leg facts and total'),
  descriptor('ArtifactSkeleton','status','Loading artifact placeholder'),
  descriptor('CoverageNotice','status','Partial resource notice'),
  descriptor('EmptyState','status','No matching fares'),
  descriptor('InlineError','status','Sanitized local failure'),
  descriptor('StaleBadge','status','Revision mismatch notice'),
  descriptor('RetryAction','status','Retry local resource operation'),
];
