import type { ComponentDescriptor } from '../contracts';
const refs = [
  {name:'artifactRef',kind:'ref',required:true}, {name:'datasetRef',kind:'ref',required:false},
  {name:'actionRef',kind:'ref',required:false}, {name:'selectorRef',kind:'ref',required:false},
  {name:'title',kind:'text',required:false}, {name:'variant',kind:'variant',required:false}, {name:'body',kind:'text',required:false},
] satisfies ComponentDescriptor['props'];
const descriptor = (name: string, group: ComponentDescriptor['group'], description: string, children = false): ComponentDescriptor => ({ name, group, description, props: refs, children });
export const descriptors: ReadonlyArray<ComponentDescriptor> = [
  descriptor('MultiCityPlanGrid','view','Connected multi-city planner for distinct city stops with an optional final return to the origin. Reads the ordered citySequence and leg datasets for one artifact; composes CityField, TravelDate, TransportSelect, FareOrder and FadeFares per leg, inserts StayDuration for each destination, and cascades selected arrival plus stay into the next leg minimum departure'),
  descriptor('FareCalendar','view','Same-leg calendar within the exact display date window. Uses the datasetRef leg, its multi-selected transport modes and host-derived minimum departure; defaults each day to its local cheapest synthetic fare, offers cheapest or fastest comparison, then opens that day fares without sending rows to the model'),
  descriptor('FadeFares','view','Same-leg horizontally scrolling synthetic fare chooser with edge fades. datasetRef binds the leg; TransportSelect, FareOrder, TravelDate and the preceding selected arrival plus StayDuration all filter and rank this local list; selections flow to the shared PlanningTracker'),
  descriptor('FareOrder','control','Same-leg fare ordering control. datasetRef binds the leg list; cheapest orders price, fastest orders duration, and departure orders service date then departure time. Cheapest and fastest also set the matching FareCalendar objective; departure leaves its default cheapest objective'),
  descriptor('TransportSelect','control','Same-leg transport selector for modes with available fares. Uses a compact multi-select dropdown with vector icons inside MultiCityPlanGrid and inline toggles when rendered alone; writes modesByLeg for the datasetRef route and filters its FadeFares and FareCalendar'),
  descriptor('StayDuration','control','Destination stay slider from 0 to 30 days. datasetRef identifies the arriving leg; its destination becomes the next leg origin, and selected arrival plus this stay sets the next minimum departure'),
  descriptor('TravelDate','control','Same-leg local departure date. datasetRef identifies the leg; the first leg changes the trip display window and later legs preserve route offsets while the host enforces any preceding arrival threshold'),
  descriptor('CityField','control','Editable origin and destination city fields backed by host location suggestions. datasetRef identifies the route positions; changes write the artifact citySequence, where each destination connects to its stay and the next leg origin'),
  descriptor('TravelHero','layout','Travel artifact headline and introduction',true),
  descriptor('Carousel','layout','Accessible horizontal panels',true),
  descriptor('DateWindow','control','Bounded local date window'),
  descriptor('FarePicker','control','Compact direct fare selector for one leg'),
  descriptor('CheapestFastest','view','Local cheapest and fastest comparison'),
  descriptor('TravelSurface','layout','Root travel artifact with subscribed local state',true),
  descriptor('Section','layout','Named story section',true),
  descriptor('Stack','layout','Vertical arrangement',true),
  descriptor('Inline','layout','Horizontal wrapping arrangement',true),
  descriptor('ResponsiveGrid','layout','Responsive equal-column arrangement',true),
  descriptor('SplitPane','layout','Responsive primary and supporting sections',true),
  descriptor('StickySummary','layout','Persistent selected-trip summary',true),
  descriptor('Tabs','layout','Accessible tabbed sections',true),
  descriptor('Callout','layout','Short heading and explanatory body text up to600 characters',true),
  descriptor('DateStrip','control','Direct local date selection'),
  descriptor('ModeChips','control','Direct local transport mode filtering'),
  descriptor('CarrierFilter','control','Direct local carrier selection'),
  descriptor('PriceRange','control','Direct local price limit'),
  descriptor('DurationRange','control','Direct local duration limit'),
  descriptor('DirectToggle','control','Direct-only local filter'),
  descriptor('SortSelect','control','Price duration or departure sorting'),
  descriptor('StayAllocation','control','Multi-city stay nights allocation'),
  descriptor('FareCards','view','Expanded fare detail cards for one leg'),
  descriptor('ComparisonTable','view','Locally resolved ranked fare comparison'),
  descriptor('ComparisonMatrix','view','Locally grouped mode comparison'),
  descriptor('PriceCalendar','view','Locally grouped price-by-day view'),
  descriptor('ModeBreakdown','view','Locally grouped option counts by transport mode'),
  descriptor('SyntheticTotal','view','Selected synthetic EUR total for all passengers'),
  descriptor('CoverageSummary','view','Resource completeness and bounds'),
  descriptor('CitySequence','view','Ordered stop strip with stay nights'),
  descriptor('RouteMap','view','Schematic connection chart'),
  descriptor('ItineraryTimeline','view','Selected adjacent-leg chronology'),
  descriptor('DurationPricePlot','view','Local duration and price comparison'),
  descriptor('SelectedItinerary','view','Selected fare route, date, mode and per-passenger facts; pair with SyntheticTotal for price summary'),
  descriptor('ArtifactSkeleton','status','Loading artifact placeholder'),
  descriptor('CoverageNotice','status','Partial resource notice'),
  descriptor('EmptyState','status','No matching fares'),
  descriptor('InlineError','status','Sanitized local failure'),
  descriptor('StaleBadge','status','Revision mismatch notice'),
  descriptor('RetryAction','status','Retry local resource operation'),
  descriptor('SelectedFareCount','view','Current artifact selected fare count, without claiming legs or price'),
];
