import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { CATALOG_VERSION } from '../contracts';
import { descriptors } from './descriptors';
const hash=createHash('sha256').update(JSON.stringify(descriptors)).digest('hex');
const content=`// Generated by npm run generate:catalog.\nimport { z } from 'zod';\nexport const catalogVersion=${JSON.stringify(CATALOG_VERSION)};\nexport const catalogHash=${JSON.stringify(hash)};\nexport const catalogDescriptors=${JSON.stringify(descriptors,null,2)} as const;\nexport const componentNames=catalogDescriptors.map(d=>d.name);\nexport const sharedPropsSchema=z.strictObject({artifactRef:z.string().min(1).max(96),datasetRef:z.string().max(96).optional(),actionRef:z.string().max(96).optional(),selectorRef:z.string().max(96).optional(),title:z.string().max(160).optional(),variant:z.enum(['default','compact','emphasis']).optional(),body:z.string().max(600).optional()});\nexport const orderedPropertyNames=['artifactRef','datasetRef','actionRef','selectorRef','title','variant'] as const;\nexport const bDefinitions=catalogDescriptors.map(descriptor=>({name:descriptor.name,description:descriptor.description,props:orderedPropertyNames}));\n`;
const docs=`# Shared catalog ${CATALOG_VERSION}\n\nManifest hash: ${hash}\n\nEvery component accepts registered scalar artifactRef, datasetRef, actionRef and selectorRef. No fare rows, arbitrary objects, URLs, code or styles are permitted. Titles have at most160 characters. Callout explanatory body text has at most600 characters; body is appended after action in B positional calls. Variant is default, compact or emphasis. B positional argument order is append-only within this version.\n\n${descriptors.map(d=>`- ${d.name}: ${d.description}${d.children ? '. May contain catalog children' : ''}.`).join('\n')}\n`;
for(const [name,value] of [['catalog.ts',content],['catalog.md',docs]]){
 const path=fileURLToPath(new URL(`./generated/${name}`,import.meta.url));
 if(process.argv.includes('--check')){ if(await readFile(path,'utf8')!==value) throw new Error(`Stale generated catalog: ${name}`); }
 else await writeFile(path,value);
}
