import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { CATALOG_VERSION } from '../contracts';
import { descriptors } from './descriptors';
const hash=createHash('sha256').update(JSON.stringify(descriptors)).digest('hex');
const content=`// Generated by npm run generate:catalog.\nimport { z } from 'zod';\nexport const catalogVersion=${JSON.stringify(CATALOG_VERSION)};\nexport const catalogHash=${JSON.stringify(hash)};\nexport const catalogDescriptors=${JSON.stringify(descriptors,null,2)} as const;\nexport const componentNames=catalogDescriptors.map(d=>d.name);\nexport const sharedPropsSchema=z.strictObject({artifactRef:z.string().min(1).max(96),datasetRef:z.string().max(96).optional(),actionRef:z.string().max(96).optional(),selectorRef:z.string().max(96).optional(),title:z.string().max(160).optional(),variant:z.enum(['default','compact','emphasis']).optional(),body:z.string().max(600).optional()});\nexport const legBoundPropsSchema=sharedPropsSchema.extend({legIndex:z.number().int().min(0).max(7)});\nexport const nodePropsSchema=sharedPropsSchema.extend({legIndex:z.number().int().min(0).max(7).optional()});\n`;
const docs=`# Shared catalog ${CATALOG_VERSION}\n\nManifest hash: ${hash}\n\nEvery component accepts registered scalar artifactRef, datasetRef, actionRef and selectorRef. Dataset-bound components also require legIndex, a zero-based integer from 0 through 7, to keep their logical leg identity through route, date and coverage changes. No fare rows, arbitrary objects, URLs, code or styles are permitted. Titles have at most160 characters. Callout explanatory body text has at most600 characters; body is appended after action in B positional calls. Variant is default, compact or emphasis. B positional argument order is append-only within this version.\n\n${descriptors.map(d=>`- ${d.name}: ${d.description}${d.children ? '. May contain catalog children' : ''}.`).join('\n')}\n`;
const nativeToolkit=`"use generative";
// Generated by npm run generate:catalog.
import { defineToolkit } from "@assistant-ui/react"
import { JSONGenerativeUI, defineGenerativeComponents } from "@assistant-ui/react-generative-ui"
import { legBoundPropsSchema, sharedPropsSchema } from "../catalog/generated/catalog"
import { CatalogNode } from "../catalog/component"
const library=defineGenerativeComponents({
${descriptors.map(descriptor=>`${descriptor.name}: { description: ${JSON.stringify(descriptor.description)}, properties: ${descriptor.props.some(prop=>prop.name==='legIndex')?'legBoundPropsSchema':'sharedPropsSchema'}, streamProperties: true, render: (props) => <CatalogNode kind=${JSON.stringify(descriptor.name)} {...props} /> },`).join('\n')}
})
const generative=new JSONGenerativeUI({library})
export default defineToolkit({present:generative.present()})
`;
for(const [relativePath,value] of [['./generated/catalog.ts',content],['./generated/catalog.md',docs],['../presentation/toolkit.tsx',nativeToolkit]]){
 const path=fileURLToPath(new URL(relativePath,import.meta.url));
 if(process.argv.includes('--check')){ if(await readFile(path,'utf8')!==value) throw new Error(`Stale generated catalog: ${relativePath}`); }
 else await writeFile(path,value);
}
