import { Children, useRef, useState, type KeyboardEvent, type ReactNode } from 'react'
import { Card } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
export type WidgetProps = { artifactRef:string; datasetRef?:string; legIndex?:number; title?:string; body?:string; variant?:'default'|'compact'|'emphasis'; actionRef?:string; selectorRef?:string; children?:ReactNode; $status?:'streaming'|'done' }
const structuralLayouts=new Set(['Section','Stack','Inline','ResponsiveGrid','SplitPane','StickySummary','Carousel'])
export function Layout({kind,...props}:WidgetProps & {kind:string}) {
  const [tab,setTab]=useState('0'); const children=Children.toArray(props.children); const tabs=useRef<Array<HTMLButtonElement|null>>([])
  const moveTab=(event:KeyboardEvent<HTMLButtonElement>,index:number)=>{if(event.altKey||event.ctrlKey||event.metaKey||event.shiftKey)return;let next:number|undefined;if(event.key==='ArrowRight')next=(index+1)%children.length;else if(event.key==='ArrowLeft')next=(index-1+children.length)%children.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=children.length-1;if(next===undefined)return;event.preventDefault();event.stopPropagation();tabs.current[next]?.focus();setTab(String(next))}
  if(kind==='Callout')return <Card role="region" aria-label={props.title} className={`travel-layout travel-callout travel-${props.variant ?? 'default'}`} data-artifact={props.artifactRef} aria-busy={props.$status==='streaming'}>{props.title&&<h3>{props.title}</h3>}{props.body&&<p>{props.body}</p>}{props.children}</Card>
  if(kind==='Tabs') return <Card className="travel-panel"><h3>{props.title ?? 'Explore options'}</h3><Tabs value={tab} onValueChange={setTab}><TabsList aria-label={props.title ?? 'Travel views'}>{children.map((_,i)=><TabsTrigger key={i} ref={element=>{tabs.current[i]=element}} value={String(i)} onKeyDown={event=>moveTab(event,i)}>View {i+1}</TabsTrigger>)}</TabsList>{children.map((child,i)=><TabsContent key={i} value={String(i)}>{child}</TabsContent>)}</Tabs></Card>
  if(structuralLayouts.has(kind))return <section role={props.title?'region':undefined} aria-label={props.title} className={`travel-layout travel-${kind.toLowerCase()} travel-${props.variant ?? 'default'}`} data-artifact={props.artifactRef} aria-busy={props.$status==='streaming'}>{props.title&&<h3>{props.title}</h3>}{props.$status==='streaming'&&!props.children?<Skeleton className="travel-skeleton" role="status">Preparing your view…</Skeleton>:props.children}</section>
  return <Card role={props.title?'region':undefined} aria-label={props.title} className={`travel-layout travel-${kind.toLowerCase()} travel-${props.variant ?? 'default'}`} data-artifact={props.artifactRef} aria-busy={props.$status==='streaming'}>{props.title && (kind==='TravelHero'?<h2>{props.title}</h2>:<h3>{props.title}</h3>)}{props.$status==='streaming'&&!props.children?<Skeleton className="travel-skeleton" role="status">Preparing your view…</Skeleton>:props.children}</Card>
}
