import{test}from'node:test'
import assert from'node:assert/strict'
import{buildMatrix,summarize,withheld,canResume,assertFixture}from'./matrix.mjs'
const scenarios=Array.from({length:12},(_,index)=>({id:`family-${index}`}))
test('full plan matrix contains 96 unique cells in balanced paired orders',()=>{const cells=buildMatrix(scenarios);assert.equal(cells.length,96);assert.equal(new Set(cells.map(cell=>cell.id)).size,96);for(let index=0;index<cells.length;index+=2){assert.equal(cells[index].scenario,cells[index+1].scenario);assert.notEqual(cells[index].variant,cells[index+1].variant);assert.deepEqual(cells[index].order,cells[index+1].order)}assert.equal(cells.filter(cell=>cell.position===0&&cell.variant==='a').length,24);assert.equal(cells.filter(cell=>cell.position===0&&cell.variant==='b').length,24);assert.equal(withheld.length,12)})
test('selected cases retain cold/warm and both wordings, and failures are summarized honestly',()=>{assert.equal(buildMatrix(scenarios,{selected:['family-3']}).length,8);assert.deepEqual(summarize([{variant:'a',outcome:'pass'},{variant:'b',outcome:'fail'}]),{cells:2,excludedFromComparison:0,passing:1,failing:1,byVariant:{a:{cells:1,passing:1},b:{cells:1,passing:0}},humanRatings:null})})

test('resume preserves completed failures and rejects another corpus or app revision',()=>{const cell=buildMatrix(scenarios)[0];const fixture={sourceVersion:'fixture-generation',rowCount:10000000};const report={...cell,fixture,fixtureValid:true,appRevision:'frozen-sha',model:'gpt-6.1-sol',reasoning:'high',provider:'signed-in-codex',liveModelAuthorship:true,outcome:'fail'};assert.equal(canResume(report,cell,'frozen-sha',fixture),true);assert.equal(canResume(report,cell,'new-sha',fixture),false);assert.equal(canResume({...report,variant:'b'},cell,'frozen-sha',fixture),false);assert.equal(canResume({...report,liveModelAuthorship:false},cell,'frozen-sha',fixture),false);assert.equal(canResume({...report,outcome:'running'},cell,'frozen-sha',fixture),false);assert.equal(canResume(report,cell,'frozen-sha',{...fixture,sourceVersion:'changed-generation'}),false);assert.equal(canResume({...report,fixtureValid:false},cell,'frozen-sha',fixture),false)})

test('fixture gate accepts only the frozen source generation and real row count',()=>{const fixture={sourceVersion:'fixture-generation',rowCount:10000000};assert.doesNotThrow(()=>assertFixture({...fixture},fixture));assert.throws(()=>assertFixture({...fixture,sourceVersion:'new-generation'},fixture),/identity changed/);assert.throws(()=>assertFixture({...fixture,rowCount:1000000},fixture),/identity changed/);assert.throws(()=>assertFixture({sourceVersion:null,rowCount:10000000},fixture),/could not be verified/)})
