import{chromium,expect}from'@playwright/test'
import{mkdir,writeFile,readFile}from'node:fs/promises'
import{buildMatrix,summarize,withheld,canResume,assertFixture,assertRuntime}from'./matrix.mjs'
import{validateReactiveProgram}from'../../../src/generative/variants/b/query/validate-program.ts'
import{validatePresentTree}from'../../../src/generative/variants/a/tree.ts'
import{createHash}from'node:crypto'
import{fareSearchDate,firstFareOption,oracleFacts,assertSourceAvailability,assertDelayedCoverage}from'./semantic-gates.mjs'
import{stableRef}from'../../../src/generative/data/resource-loader.ts'
const budgets={httpCallMs:180000,visibleTurnMs:600000,wholeCellMs:1800000}
const sleep=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds))
function analyzeSource(scene){
 try{
  if(scene.toolName==='present'){const root=validatePresentTree(scene.input),types=[];const walk=node=>{types.push(node.$type);const children=Array.isArray(node.children)?node.children:typeof node.children==='object'&&node.children?[node.children]:[];return{type:node.$type,variant:node.variant??null,selectorRef:node.selectorRef??null,actionRef:node.actionRef??null,children:children.filter(child=>typeof child==='object').map(walk)}};const shape=walk(root);return{valid:true,componentTypes:types,shape,structuralHash:createHash('sha256').update(JSON.stringify(shape)).digest('hex')}}
  const result=validateReactiveProgram(scene.input.program),queries=result.parsed.queryStatements.map(query=>({id:query.statementId,deps:query.deps,argsAST:query.argsAST}));const graph={variables:result.variables,bindings:result.bindings.map(({artifactRef,datasetRef,...binding})=>binding),dependencies:result.dependencies,queryBindings:result.queryBindings.map(({artifactRef,datasetRef,...binding})=>binding),queryStatements:queries,mutationCount:result.parsed.mutationStatements.length};return{valid:true,...graph,structuralHash:createHash('sha256').update(JSON.stringify(graph).replace(/dataset-[a-z0-9]+/g,'dataset-ref')).digest('hex')}
 }catch(error){return{valid:false,error:String(error.message??error)}}
}
const baseline='Load London to Paris for October 9–15, 2026, one passenger, all train bus flight ferry modes. In the active travel artifact show local mode buttons, departure-date control, sorting, selectable fare cards, a price calendar and selected itinerary with synthetic total. Put controls before offers. Explain briefly before and after the view.'
async function saved(page,variant){return page.evaluate(variant=>new Promise((resolve,reject)=>{const open=indexedDB.open('omio-generative-state',1);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const get=open.result.transaction('threads').objectStore('threads').get(`travel-${variant}`);get.onsuccess=()=>resolve(get.result);get.onerror=()=>reject(get.error)}}),variant)}
async function settled(page,record){await expect.poll(async()=>{const value=await saved(page,record.variant);return Boolean(value?.artifacts.length)},{timeout:15000}).toBe(true);await sleep(120);return saved(page,record.variant)}
async function warm(page,variant){return page.evaluate(async variant=>{
 const{createFareDataBridge}=await import('/src/generative/data/fare-data-bridge.ts');const{createUIStateStore}=await import('/src/generative/state/ui-state-store.ts');const{createThreadPersistence}=await import('/src/generative/state/persistence.ts');const bridge=createFareDataBridge(),store=createUIStateStore(),request={originIds:['london'],destinationIds:['paris'],dateWindow:{from:'2026-10-09',to:'2026-10-15'},modes:['train','bus','flight','ferry'],passengers:1};const start=performance.now(),manifest=await bridge.load(request,new AbortController().signal),id='study-artifact';store.initializeMissing(id,{dates:{start:'2026-10-09'},datasetRefs:[manifest.datasetId]});await createThreadPersistence().save(`travel-${variant}`,{schemaVersion:'1.0.0',catalogVersion:'1.0.0',parserVersion:'openui-0.3.0',queryVersion:'1',activeArtifactId:id,messages:[],artifacts:[{variant,source:'No scene authored yet.',state:store.get(id)}],descriptors:[{datasetId:manifest.datasetId,request,sourceVersion:manifest.source.sourceVersion,complete:manifest.coverage.complete}]});return{elapsedMs:performance.now()-start,manifest}
 },variant)}
export function instrument(){
 const document=window.document
 const metrics={started:0,firstText:null,firstUI:null,firstControl:null,queries:[],resources:[],longTasks:[],interactionToPaintMs:[],interactionStart:null,workerMemory:null,baselineViews:0};window.__studyMetrics=metrics
 const originalFetch=window.fetch.bind(window);window.fetch=async(...args)=>{const response=await originalFetch(...args);const url=typeof args[0]==='string'?args[0]:args[0]?.url;if(!url?.endsWith('/api/chat')||!response.body)return response;let remainder='';const decoder=new TextDecoder();return new Response(response.body.pipeThrough(new TransformStream({transform(chunk,controller){remainder+=decoder.decode(chunk,{stream:true});const lines=remainder.split('\n');remainder=lines.pop()??'';for(const line of lines)if(line.startsWith('data: {')){try{const event=JSON.parse(line.slice(6));if(event.type==='text-delta'&&metrics.started&&metrics.firstText===null)metrics.firstText=performance.now()-metrics.started}catch{}}controller.enqueue(chunk)}})),{status:response.status,statusText:response.statusText,headers:response.headers})}
 const WorkerOriginal=window.Worker;window.Worker=class extends WorkerOriginal{constructor(...args){super(...args);const pending=new Map(),scopes=new Map();const post=this.postMessage.bind(this);this.postMessage=(message,...rest)=>{if(message.kind==='register')metrics.resources.push({datasetId:message.datasetId,rowCount:message.resource.rows.length,sourceVersion:message.resource.sourceVersion,revision:message.resource.revision});if(message.kind==='query')scopes.set(message.id,message.query);if(message.kind==='query'||message.kind==='cancel')pending.set(`${message.kind}:${message.id}`,performance.now());return post(message,...rest)};this.addEventListener('message',event=>{const message=event.data,start=pending.get(`query:${message.id}`);if(start!==undefined){metrics.queries.push({durationMs:performance.now()-start,status:message.kind,scope:scopes.get(message.id)??null,resultTotal:message.result?.total??0,resultDates:[...new Set((message.result?.rows??[]).map(row=>row.serviceDate).filter(value=>typeof value==='string'))].slice(0,14),code:message.code??null,resultRows:message.result?.rows?.length??0,resultFareRows:(message.result?.rows??[]).filter(row=>typeof row.id==='string'&&typeof row.priceCents==='number').length,resultBytes:message.result?new TextEncoder().encode(JSON.stringify(message.result)).length:0,cancelAckMs:pending.has(`cancel:${message.id}`)?performance.now()-pending.get(`cancel:${message.id}`):null});pending.delete(`query:${message.id}`);scopes.delete(message.id)}})}}
 try{new PerformanceObserver(list=>metrics.longTasks.push(...list.getEntries().map(entry=>({duration:entry.duration,start:entry.startTime})))).observe({type:'longtask',buffered:true})}catch{}
 for(const type of['click','input','change','keydown'])document.addEventListener(type,event=>{if(event.target instanceof Element&&event.target.closest('.travel-travelsurface'))metrics.interactionStart=performance.now()},true)
 new MutationObserver(()=>{if(metrics.interactionStart!==null){const start=metrics.interactionStart;metrics.interactionStart=null;requestAnimationFrame(()=>metrics.interactionToPaintMs.push(performance.now()-start))}if(!metrics.started)return;const elapsed=performance.now()-metrics.started;const views=Array.from(document.querySelectorAll('.travel-travelsurface')).slice(metrics.baselineViews);if(metrics.firstUI===null&&views.length)metrics.firstUI=elapsed;if(metrics.firstControl===null&&views.some(view=>view.querySelector('button,input,select')))metrics.firstControl=elapsed}).observe(document,{subtree:true,childList:true,characterData:true})
}
async function send(page,recorder,prompt,{wait=true}={}){const start=Date.now(),offset=recorder.requests.length;await page.evaluate(()=>{window.__studyMetrics.baselineViews=document.querySelectorAll('.travel-travelsurface').length;window.__studyMetrics.started=performance.now();window.__studyMetrics.firstText=null;window.__studyMetrics.firstUI=null;window.__studyMetrics.firstControl=null});await page.getByRole('textbox',{name:'Message'}).fill(prompt);await page.getByRole('button',{name:'Send message'}).click();await expect.poll(()=>recorder.requests.length,{timeout:15000}).toBeGreaterThan(offset);if(wait)await idle(recorder);return{elapsedMs:Date.now()-start,requestOffset:offset,prompt}}
async function idle(recorder){const deadline=Math.min(Date.now()+budgets.visibleTurnMs,recorder.cellDeadline);while(Date.now()<deadline){await sleep(200);if([...recorder.pending].some(request=>Date.now()-(recorder.callStarted.get(request)??Date.now())>budgets.httpCallMs))throw new Error('Live HTTP call exceeded declared180second budget');if(!recorder.pending.size&&Date.now()-recorder.last>1000)return}throw new Error('Live visible turn or cell exceeded declared time budget')}
async function ensurePressed(control,value=true){if((await control.getAttribute('aria-pressed'))!==String(value))await control.click();await expect(control).toHaveAttribute('aria-pressed',String(value))}
async function checkNoChat(recorder,action){const before=recorder.requests.length,start=Date.now();await action();await sleep(150);expect(recorder.requests.length).toBe(before);return{elapsedMs:Date.now()-start,modelRequestDelta:0}}

async function onlyMode(view,label){for(const name of['Train','Bus','Flight','Ferry'])await ensurePressed(view.getByRole('button',{name,exact:true}).first(),name===label)}
export async function chooseFare(view){
 const picker=view.getByRole('combobox',{name:'Choose a synthetic fare',exact:true}).first();
 if(await picker.count()){
  await expect(picker).toBeVisible();await expect.poll(()=>picker.locator('option').count(),{timeout:30000}).toBeGreaterThan(1);
  const option=firstFareOption(await picker.locator('option').evaluateAll(nodes=>nodes.map(node=>({value:node.value,label:node.textContent??''}))));
  const before=await picker.inputValue();if(before){await picker.selectOption('');await expect(picker).toHaveValue('');}await picker.focus();await expect(picker).toBeFocused();await picker.press(option.label[0]);await picker.press('Enter');await expect.poll(()=>picker.inputValue()).not.toBe('');const fareId=await picker.inputValue();expect(await picker.locator('option').evaluateAll((nodes,value)=>nodes.some(node=>node.value===value&&Boolean(node.value)),fareId)).toBe(true);
  return{control:'native fare select',keyboard:true,fareId,previousFareId:before};
 }
 const button=view.getByRole('button',{name:/^Select /}).first();await expect(button).toBeVisible();await button.focus();await expect(button).toBeFocused();await button.press('Enter');await expect(button).toHaveAttribute('aria-pressed','true');return{control:'native fare card',keyboard:true};
}
export async function sourceGate(page,recorder,cell,date){
 let proof;
 await expect.poll(async()=>{
  try{
   const record=await settled(page,cell),state=(record.artifacts.find(item=>item.state.artifactId===record.activeArtifactId)??record.artifacts.at(-1)).state,source=await recorder.oracle(state,date);
   const visibleDataCount=await page.locator('.travel-travelsurface').last().evaluate(root=>root.querySelectorAll('.travel-fares article,select[aria-label="Choose a synthetic fare"] option:not([value=""]),.travel-calendar button,.travel-table tbody tr,.travel-dot').length+[...root.querySelectorAll('.travel-insight strong')].filter(node=>/[€£$0-9]/.test(node.textContent??'')).length+[...root.querySelectorAll('.travel-timeline li')].filter(node=>/2026-\d\d-\d\d/.test(node.textContent??'')).length);
   const metrics=await page.evaluate(()=>window.__studyMetrics);
   proof=assertSourceAvailability({state,descriptors:record.descriptors,queries:metrics.queries.slice(recorder.targetQueryOffset??0),availableCount:source.filteredCount,visibleDataCount,sourceVersion:recorder.sourceVersion,expectedDate:date,requireSingleDate:cell.requireSingleDate===true||['local-controls','coverage','reload','date-sort-reload'].includes(cell.scenario)});
   proof.workerRegistrations=metrics.resources.filter(resource=>proof.datasetRefs.includes(resource.datasetId));
   return true;
  }catch{return false}
 },{timeout:30000}).toBe(true);
 return proof;
}
export async function interactions(page,recorder,cell){
 const result={},views=page.locator('.travel-travelsurface'),bus=()=>views.last().getByRole('button',{name:'Bus',exact:true}).first(),date=()=>views.last().locator('input[type=date]').first(),sort=()=>views.last().locator('select:has(option[value="durationMinutes:asc"])').first()
 if(['cheap-fast','train-bus','calendar','multi-city'].includes(cell.scenario)){
  await expect(views.last()).toBeVisible();expect(await views.last().locator('section,fieldset,table,svg,article').count()).toBeGreaterThan(2)
  result.sourceAvailability=await sourceGate(page,recorder,cell,'2026-10-09')
  if(cell.scenario==='calendar')expect(await views.last().locator('.travel-calendar button').count()).toBeGreaterThan(0)
  if(cell.scenario==='multi-city'){const record=await settled(page,cell);expect(record.artifacts.some(item=>item.state.stays.some(stay=>stay.cityId==='paris'&&stay.nights===2))).toBe(true);expect(record.descriptors.some(item=>item.request.originIds.includes('paris')&&item.request.destinationIds.includes('barcelona'))).toBe(true)}
 }
 if(cell.scenario==='rearrange'){await expect(views.last().locator('.travel-timeline').first()).toBeVisible();result.sourceAvailability=await sourceGate(page,recorder,cell,'2026-10-09');result.retainedState=await settled(page,cell)}
 if(cell.scenario==='text-state'){const response=recorder.responses.slice(recorder.targetResponseOffset);expect(response.flatMap(item=>item.events).some(event=>event.type.startsWith('tool-input'))).toBe(false);expect(await views.count()).toBe(recorder.initialViews);const snapshot=recorder.requests[recorder.targetRequestOffset]?.body.currentContext;expect(snapshot.artifacts.some(artifact=>artifact.filters.modes.includes('bus')||Object.values(artifact.modesByLeg).some(modes=>modes.includes('bus')))).toBe(true);result.latestSnapshot=snapshot}
 if(cell.scenario==='local-controls'||cell.scenario==='reload'){
  result.local=await checkNoChat(recorder,async()=>{await onlyMode(views.last(),'Bus');await date().fill('2026-10-10');await sort().selectOption('durationMinutes:asc');result.sourceAvailability=await sourceGate(page,recorder,cell,'2026-10-10');result.fareSelection=await chooseFare(views.last())});const record=await settled(page,cell);expect(record.artifacts.some(item=>item.state.selectedFareIds.length===1&&item.state.sort.field==='durationMinutes')).toBe(true)
  if(cell.scenario==='reload'){
   await page.reload();recorder.targetQueryOffset=0;await expect(views.last()).toBeVisible();result.reloadedSourceAvailability=await sourceGate(page,recorder,cell,'2026-10-10');expect((await settled(page,cell)).artifacts.map(item=>item.state.selectedFareIds)).toEqual(record.artifacts.map(item=>item.state.selectedFareIds));result.completeReload=true
   result.partialCoverage=await page.evaluate(async variant=>{const{createFareDataBridge}=await import('/src/generative/data/fare-data-bridge.ts');const{createThreadPersistence}=await import('/src/generative/state/persistence.ts');const persistence=createThreadPersistence(),thread=await persistence.load(`travel-${variant}`),descriptor=thread.descriptors[0],bridge=createFareDataBridge({maxRows:5}),manifest=await bridge.load(descriptor.request,new AbortController().signal);if(manifest.coverage.complete)throw new Error('Expected actualboundedpartialresource');descriptor.complete=false;await persistence.save(`travel-${variant}`,thread);return{complete:manifest.coverage.complete,rowCount:manifest.rowCount,sourceVersion:manifest.source.sourceVersion}},cell.variant);await page.reload();recorder.targetQueryOffset=0;await expect(views.last()).toBeVisible();expect((await settled(page,cell)).artifacts.map(item=>item.state.selectedFareIds)).toEqual(record.artifacts.map(item=>item.state.selectedFareIds));result.partialReload=true;result.partialHydrationAvailability=await sourceGate(page,recorder,cell,'2026-10-10');expect(result.partialHydrationAvailability.workerRegistrations.some(resource=>resource.rowCount>result.partialCoverage.rowCount&&resource.sourceVersion===recorder.sourceVersion)).toBe(true)
  }
 }
 if(cell.scenario==='coverage'){
  let intercepted=0,completed=0,fulfilled=0,canceled=0;await page.route('**/api/search?**',async route=>{if(fareSearchDate(route.request().url())==='2026-10-20'){intercepted++;const response=await route.fetch();await sleep(800);try{await route.fulfill({response});fulfilled++}catch{canceled++}finally{completed++}return}await route.continue()});result.local=await checkNoChat(recorder,async()=>{await date().fill('2026-10-20');await expect.poll(()=>intercepted,{timeout:15000}).toBeGreaterThan(0);await date().fill('2026-10-22');await expect.poll(()=>completed,{timeout:15000}).toBeGreaterThan(0);result.sourceAvailability=await sourceGate(page,recorder,cell,'2026-10-22')});const record=await settled(page,cell);expect(record.artifacts.at(-1).state.dates.start).toBe('2026-10-22');expect(record.descriptors.filter(item=>record.artifacts.at(-1).state.datasetRefs.includes(item.datasetId)).some(item=>item.request.dateWindow.from==='2026-10-20')).toBe(false);result.delayedCoverage=assertDelayedCoverage({intercepted,completed,fulfilled,canceled,latestDate:record.artifacts.at(-1).state.dates.start,activeWindowStarts:record.descriptors.filter(item=>record.artifacts.at(-1).state.datasetRefs.includes(item.datasetId)).map(item=>item.request.dateWindow.from)});result.latestDate='2026-10-22'
 }
 if(cell.scenario==='stream-edit'){expect(recorder.editedDuringStream).toBe(true);await expect(bus()).toHaveAttribute('aria-pressed',String(recorder.streamExpectedPressed));result.editDuringStream=true;result.sourceAvailability=await sourceGate(page,recorder,cell,'2026-10-09')}
 if(cell.scenario==='two-artifacts'){
  const record=await settled(page,cell);expect(record.artifacts.length).toBeGreaterThan(1);const ids=record.artifacts.map(item=>item.state.artifactId),first=page.locator(`[data-artifact="${ids[0]}"]`).first(),second=page.locator(`[data-artifact="${ids.at(-1)}"]`).first();result.local=await checkNoChat(recorder,async()=>{await onlyMode(first,'Bus');await onlyMode(second,'Train')});const after=await settled(page,cell);expect(JSON.stringify(after.artifacts[0].state.filters)+JSON.stringify(after.artifacts[0].state.modesByLeg)).not.toBe(JSON.stringify(after.artifacts.at(-1).state.filters)+JSON.stringify(after.artifacts.at(-1).state.modesByLeg));expect(after.artifacts[0].state.datasetRefs.some(ref=>after.artifacts.at(-1).state.datasetRefs.includes(ref))).toBe(true);result.independentSharedResourceViews=true;result.sourceAvailability=await sourceGate(page,recorder,cell,'2026-10-09')
 }
 if(cell.scenario==='recovery'){
  const before=await views.count();await send(page,recorder,'Replace the layout with a large calendar and route timeline, retaining my choices.',{wait:false});await page.getByRole('button',{name:'Stop response'}).click();await expect(page.getByRole('button',{name:'Stop response'})).toBeDisabled();await expect(views.first()).toBeVisible();expect(await views.count()).toBeGreaterThanOrEqual(before);result.cancelPreservedView=true
  const retryOffset=recorder.requests.length;await page.getByRole('button',{name:'Retry response'}).last().click();await expect.poll(()=>recorder.requests.length,{timeout:15000}).toBeGreaterThan(retryOffset);await idle(recorder);await expect(views.last()).toBeVisible();result.retryCompleted=true;result.sourceAvailability=await sourceGate(page,recorder,cell,'2026-10-09');result.invalidOutputGate='separate recorded deterministic one-repair tests; live invalid model outputs retained when naturally observed'
 }
 return result
}
export async function runMatrix(scenarios){
 const cells=buildMatrix(scenarios,{selected:(process.env.OMIO_SCENARIOS??'all').split(','),seed:Number(process.env.OMIO_WITHHELD_SEED??17)});if(process.argv.includes('--dry-run')){console.log(JSON.stringify({cells,modelCalls:0},null,2));return}
 const appRevision=process.env.OMIO_APP_REVISION;if(!appRevision)throw new Error('Set OMIO_APP_REVISION to the frozen preview commit before live model calls')
 const expectedRuntime={appRevision,provider:'signed-in-codex',model:'gpt-6.1-sol',reasoningEffort:'high'};const base=process.env.OMIO_DEMO_URL??'http://127.0.0.1:5194',fixture={sourceVersion:process.env.OMIO_SOURCE_VERSION,rowCount:Number(process.env.OMIO_FIXTURE_ROWS)};if(!fixture.sourceVersion||!Number.isSafeInteger(fixture.rowCount))throw new Error('Pin OMIO_SOURCE_VERSION and OMIO_FIXTURE_ROWS from verified /api/health before live calls');const readFixture=async()=>{const response=await fetch(`${base}/api/health`,{signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('Authoritative fixture health unavailable');const health=await response.json();return{sourceVersion:health.source_version,rowCount:health.fare_count}};assertFixture(await readFixture(),fixture)
 const readRuntime=async()=>{const response=await fetch(`${base}/api/agent/health`,{signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('Authoritative agent health unavailable');return assertRuntime(await response.json(),expectedRuntime)};const runtime=await readRuntime()
 if(process.argv.includes('--preflight')){const result={runtime,fixture,cells:cells.length,modelCalls:0};console.log(JSON.stringify(result));return result}
 const output=process.env.OMIO_EXPERIMENT_OUTPUT??'verification/generative-ui/study/artifacts';await mkdir(output,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const reports=[];const activeContexts=new Set();let fixtureDrift=null,runtimeDrift=null,checkingIdentity=false;const verifyIdentity=async()=>{if(fixtureDrift||runtimeDrift)throw new Error(runtimeDrift??fixtureDrift);try{assertFixture(await readFixture(),fixture)}catch(error){fixtureDrift=String(error.message??error);throw error}try{const observed=await readRuntime();if(fixtureDrift||runtimeDrift)throw new Error(runtimeDrift??fixtureDrift);return observed}catch(error){runtimeDrift??=String(error.message??error);throw error}};const abortActive=()=>{for(const context of activeContexts)void context.close()};const identityMonitor=setInterval(async()=>{if(checkingIdentity||fixtureDrift||runtimeDrift)return;checkingIdentity=true;try{await verifyIdentity()}catch{abortActive()}finally{checkingIdentity=false}},5000);const completed=new Set();for(const cell of cells){try{const previous=JSON.parse(await readFile(`${output}/${cell.id}.json`,'utf8'));if(canResume(previous,cell,runtime,fixture)){reports.push(previous);completed.add(cell.id)}}catch{}}let next=0
 const pairs=Array.from({length:cells.length/2},(_,index)=>cells.slice(index*2,index*2+2));const concurrency=Math.min(3,Math.max(1,Number(process.env.OMIO_CONCURRENCY??3)))
 async function cellRun(cell){if(completed.has(cell.id)||fixtureDrift||runtimeDrift)return;try{await verifyIdentity()}catch{abortActive();return}const started=Date.now(),context=await browser.newContext({viewport:{width:1280,height:1000},reducedMotion:'reduce'});activeContexts.add(context);await context.addInitScript(instrument);await context.tracing.start({screenshots:true,snapshots:true,sources:true});const page=await context.newPage(),recorder={requests:[],responses:[],pending:new Set(),last:Date.now(),errors:[],targetRequestOffset:0,targetResponseOffset:0,initialViews:0,editedDuringStream:false,callStarted:new Map(),cellDeadline:started+budgets.wholeCellMs,sourceVersion:fixture.sourceVersion};recorder.oracle=async(state,date)=>{const params=new URLSearchParams({origin:'london',destination:'paris',departure_date:date,passengers:'1',limit:'100'}),response=await fetch(`${base}/api/search?${params}`,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Source availability oracle failed');const data=await response.json();if(data.source_version!==fixture.sourceVersion||data.outbound.pages>1)throw new Error('Source availability oracle changed or exceeded bounded one-page fixture');const facts=data.outbound.results.map(row=>({id:row.id,serviceDate:data.outbound.date,mode:row.mode,carrierId:`carrier-${stableRef(row.company)}`,priceCents:row.price_cents,durationMinutes:row.duration_minutes,direct:true}));return{filteredCount:oracleFacts(facts,{...state.filters,modes:state.modesByLeg['london:paris']??state.filters.modes}).length}};const cellTimer=setTimeout(()=>{recorder.budgetExceeded='whole-cell';void context.close()},budgets.wholeCellMs);const map=new Map();page.on('pageerror',error=>recorder.errors.push(error.message));page.on('request',request=>{if(request.url().endsWith('/api/chat')){const entry={body:request.postDataJSON(),startedMs:Date.now()-started,bytes:Buffer.byteLength(request.postData()??'')};recorder.requests.push(entry);map.set(request,entry);recorder.pending.add(request);recorder.callStarted.set(request,Date.now());recorder.last=Date.now()}});page.on('requestfailed',request=>{recorder.pending.delete(request);recorder.last=Date.now()});page.on('response',async response=>{if(response.url().endsWith('/api/chat')){try{const body=await response.text();recorder.responses.push({status:response.status(),elapsedMs:Date.now()-started,events:body.split('\n').filter(line=>line.startsWith('data: {')).map(line=>JSON.parse(line.slice(6)))});}catch{}finally{recorder.pending.delete(response.request());recorder.last=Date.now()}}});
  let report={...cell,appRevision:runtime.appRevision,runtime,runtimeValid:true,fixture,fixtureValid:true,independentContexts:concurrency,viewport:{width:1280,height:1000},reducedMotion:'reduce',model:runtime.model,reasoning:runtime.reasoningEffort,provider:runtime.provider,supportedModelSeed:null,temperature:null,networkShaping:'none except explicit800msoldercoverage fault',coldDefinition:'fresh browser/worker, no restored descriptors; backend SQLite and signed-in model service shared',warmDefinition:'same normalized coverage descriptor preloaded and restored before the live task; no replayed scene or extra layout model',liveModelAuthorship:true,humanRatings:null,tokenUsage:null,budgets,outcome:'fail'}
  try{
   await page.route('**/api/chat',async route=>{try{await verifyIdentity()}catch{await route.abort().catch(()=>{});abortActive();return}await route.continue().catch(()=>{})})
   await page.goto(`${base}/${cell.variant}`);await page.getByRole('textbox',{name:'Message'}).waitFor();if(cell.cache==='warm'){report.preload=await warm(page,cell.variant);await page.reload();await page.getByRole('textbox',{name:'Message'}).waitFor()}
   if(cell.index>=4){report.prerequisite=await send(page,recorder,baseline);await expect(page.locator('.travel-travelsurface').last()).toBeVisible();if(cell.scenario==='text-state'){await onlyMode(page.locator('.travel-travelsurface').last(),'Bus');await sourceGate(page,recorder,cell,'2026-10-09');await chooseFare(page.locator('.travel-travelsurface').last());await sleep(200)}}
   recorder.targetQueryOffset=await page.evaluate(()=>window.__studyMetrics.queries.length);recorder.initialViews=await page.locator('.travel-travelsurface').count();recorder.targetRequestOffset=recorder.requests.length;recorder.targetResponseOffset=recorder.responses.length;const prompt=cell.wording==='fixed'?scenarios[cell.index].prompt:withheld[cell.index]
   if(cell.scenario==='stream-edit'){report.target=await send(page,recorder,prompt,{wait:false});await expect(page.getByRole('button',{name:'Stop response'})).toBeEnabled();const control=page.getByRole('button',{name:'Bus',exact:true}).first();recorder.streamExpectedPressed=(await control.getAttribute('aria-pressed'))!=='true';await control.click();recorder.editedDuringStream=recorder.pending.size>0;await idle(recorder)}else report.target=await send(page,recorder,prompt)
   report.actions=await interactions(page,recorder,cell);expect(recorder.errors).toEqual([]);expect(await page.getByText('These options could not load. Try refreshing the view.',{exact:true}).count()).toBe(0);expect(await page.getByText('This generated view could not be applied. The last usable view remains available; ask the assistant to repair it.',{exact:true}).count()).toBe(0);expect(await page.getByText('This generated view could not be completed. Your current travel view remains available.',{exact:true}).count()).toBe(0);expect(await page.getByText('Preparing reactive view…',{exact:true}).count()).toBe(0);expect(recorder.responses.every(response=>response.status===200)).toBe(true);report.outcome='pass'
  }catch(error){report.failure=String(error.message??error).slice(0,3000);try{await page.getByRole('button',{name:'Stop response'}).click({timeout:500})}catch{}}
  if(!fixtureDrift&&!runtimeDrift){try{await verifyIdentity()}catch{abortActive()}}if(fixtureDrift||runtimeDrift){report.outcome='fail';report.fixtureValid=!fixtureDrift;report.runtimeValid=!runtimeDrift;report.excludedFromComparison=true;report.failure=runtimeDrift??fixtureDrift}report.elapsedMs=Date.now()-started;report.requests=recorder.requests;report.responses=recorder.responses;report.pageErrors=recorder.errors;report.metrics=await page.evaluate(()=>window.__studyMetrics).catch(()=>null);if(report.metrics){const durations=report.metrics.queries.map(query=>query.durationMs).sort((a,b)=>a-b),percentile=p=>durations.length?durations[Math.min(durations.length-1,Math.ceil(durations.length*p)-1)]:null;report.metrics.queryP50Ms=percentile(.5);report.metrics.queryP95Ms=percentile(.95);report.metrics.mainThreadLongTaskCount=report.metrics.longTasks.length;report.metrics.workerMemoryMeasurement='unavailable in browser Worker API';}report.persisted=await saved(page,cell.variant).catch(()=>null);report.sceneInputs=recorder.responses.flatMap(response=>response.events.filter(event=>event.type==='tool-input-available'&&['present','compose_reactive_scene'].includes(event.toolName)).map(event=>({toolName:event.toolName,input:event.input})));report.targetSceneInputs=recorder.responses.slice(recorder.targetResponseOffset).flatMap(response=>response.events.filter(event=>event.type==='tool-input-available'&&['present','compose_reactive_scene'].includes(event.toolName)).map(event=>({toolName:event.toolName,input:event.input})));report.sourceAnalysis=report.sceneInputs.map(analyzeSource);report.targetSourceAnalysis=report.targetSceneInputs.map(analyzeSource);report.repairEvents=recorder.responses.flatMap(response=>response.events.filter(event=>event.type==='tool-input-error'||event.type==='error'));await page.screenshot({path:`${output}/${cell.id}.png`,fullPage:true}).catch(()=>{});clearTimeout(cellTimer);await context.tracing.stop({path:`${output}/${cell.id}.trace.zip`}).catch(()=>{});await writeFile(`${output}/${cell.id}.json`,JSON.stringify(report,null,2));reports.push(report);await writeFile(`${output}/results.json`,JSON.stringify({timestamp:new Date().toISOString(),browser:browser.version(),summary:summarize(reports),planned:cells.length,fixture,appRevision,runtime,fixtureDrift,runtimeDrift,reports:reports.map(({requests,responses,persisted,...summary})=>summary)},null,2));console.log(JSON.stringify({id:cell.id,outcome:report.outcome,elapsedMs:report.elapsedMs,requests:recorder.requests.length,failure:report.failure??null,finished:reports.length,total:cells.length}));activeContexts.delete(context);await context.close()
 }
 try{await Promise.all(Array.from({length:concurrency},async()=>{while(next<pairs.length&&!fixtureDrift&&!runtimeDrift){const pair=pairs[next++];for(const cell of pair)await cellRun(cell)}}))}finally{clearInterval(identityMonitor);await browser.close();await writeFile(`${output}/run-status.json`,JSON.stringify({appRevision,runtime,fixture,fixtureDrift,runtimeDrift,planned:cells.length,finished:reports.length,remaining:cells.length-reports.length,summary:summarize(reports)},null,2))}
}
