import{test}from'node:test';
import assert from'node:assert/strict';
import{fareSearchDate,assertSourceAvailability,firstFareOption,oracleFacts,assertDelayedCoverage}from'./semantic-gates.mjs';
const descriptor={datasetId:'dataset-route',sourceVersion:'fixture',request:{originIds:['london'],destinationIds:['paris'],dateWindow:{from:'2026-10-09',to:'2026-10-15'},modes:['train','bus','flight','ferry'],passengers:1}};
const query={scope:{sources:[{datasetRef:'dataset-route'}],where:{field:'serviceDate',op:'eq',value:'2026-10-10'}},status:'result',resultFareRows:3,resultRows:3,resultTotal:3,resultDates:['2026-10-10']};
const sample={state:{dates:{start:'2026-10-10'},datasetRefs:['dataset-route']},descriptors:[descriptor],queries:[query],availableCount:28,visibleDataCount:3,sourceVersion:'fixture',expectedDate:'2026-10-10'};
test('delayed coverage fault matches real serialized API departure date only',()=>{assert.equal(fareSearchDate('http://localhost/api/search?origin=london&destination=paris&departure_date=2026-10-20&mode=all'),'2026-10-20');assert.equal(fareSearchDate('http://localhost/api/search?date=2026-10-20'),null);assert.equal(fareSearchDate('http://localhost/other?departure_date=2026-10-20'),null)});
test('source availability rejects a false empty view or wrong loaded date window',()=>{assert.equal(assertSourceAvailability(sample).availableCount,28);assert.throws(()=>assertSourceAvailability({...sample,queries:[{...query,resultRows:0,resultTotal:0,resultDates:[]}]}),/available source fares/);assert.throws(()=>assertSourceAvailability({...sample,descriptors:[{...descriptor,request:{...descriptor.request,dateWindow:{from:'2026-10-02',to:'2026-10-08'}}}]}),/loaded coverage/);assert.throws(()=>assertSourceAvailability({...sample,queries:[{...query,scope:{...query.scope,sources:[{datasetRef:'wrong-resource'}]}}]}),/available source fares/);assert.throws(()=>assertSourceAvailability({...sample,visibleDataCount:0}),/available source fares/);assert.equal(assertSourceAvailability({...sample,availableCount:0,queries:[{...query,resultRows:0,resultTotal:0}]}).legitimateEmpty,true)});
test('fare-picker option choice stays within actual native selectable values',()=>{assert.deepEqual(firstFareOption([{value:'',label:'No fare selected'},{value:'fare_1',label:'Bus · Example'}]),{value:'fare_1',label:'Bus · Example'});assert.throws(()=>firstFareOption([{value:'',label:'No fare selected'}]),/No selectable fare/)});
test('source oracle applies the actual selected modes and finite user filters',()=>{const rows=[{id:'one',serviceDate:'2026-10-10',mode:'bus',carrierId:'carrier-a',priceCents:2000,durationMinutes:300},{id:'two',serviceDate:'2026-10-10',mode:'train',carrierId:'carrier-b',priceCents:4000,durationMinutes:120}];assert.equal(oracleFacts(rows,{modes:['bus'],carrierIds:[]}).length,1);assert.equal(oracleFacts(rows,{modes:['ferry'],carrierIds:[]}).length,0);assert.equal(oracleFacts(rows,{modes:[],carrierIds:[],maxPriceCents:1000}).length,0);assert.equal(oracleFacts(rows,{modes:[],carrierIds:[],maxDurationMinutes:200}).length,1)});

test('delayed coverage rejects the previous never-fired date matcher and late state overwrite',()=>{const request='/api/search?departure_date=2026-10-20';const oldMatched=new URL(request,'http://localhost').searchParams.get('date')==='2026-10-20';const facts={intercepted:Number(oldMatched),completed:Number(oldMatched),fulfilled:Number(oldMatched),canceled:0,latestDate:'2026-10-22',activeWindowStarts:['2026-10-22']};assert.throws(()=>assertDelayedCoverage(facts),/never completed/);const corrected={...facts,intercepted:Number(fareSearchDate(request)==='2026-10-20'),completed:1,fulfilled:1};assert.equal(assertDelayedCoverage(corrected).lateCompletionIgnored,true);assert.throws(()=>assertDelayedCoverage({...corrected,activeWindowStarts:['2026-10-20']}),/older delayed coverage/);assert.equal(assertDelayedCoverage({...corrected,fulfilled:0,canceled:1}).canceled,1)});

test('departure action rejects authored literal or broad fare query even when the snapshot date changes',()=>{assert.equal(assertSourceAvailability({...sample,requireSingleDate:true}).availableCount,28);assert.throws(()=>assertSourceAvailability({...sample,requireSingleDate:true,queries:[{...query,scope:{...query.scope,where:{field:'serviceDate',op:'between',value:['2026-10-09','2026-10-15']}},resultDates:['2026-10-09','2026-10-10']}]}),/exactly the latest date/);assert.throws(()=>assertSourceAvailability({...sample,requireSingleDate:true,queries:[{...query,resultFareRows:0}]}),/exactly the latest date/)});
