import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{analyzeSource,analyzeAuthorshipCorpus,timelineRevealActions}from'./source-analysis.mjs';
const a=children=>({toolName:'present',input:{$type:'TravelSurface',artifactRef:'artifact-test',title:'Heading',children}}),node=name=>({$type:name,artifactRef:'artifact-test'}),b=program=>analyzeSource({toolName:'compose_reactive_scene',input:{program}}),program=readFileSync('verification/generative-ui/b/live/program-1.openui','utf8');
test('source analysis excludes cosmetic A labels, keys and refs but preserves recursive arrangement',()=>{const first=analyzeSource(a([{$type:'Section',artifactRef:'artifact-test',children:[node('PriceCalendar'),node('FarePicker')]}]));const labelOnly=structuredClone(a([{$type:'Section',artifactRef:'artifact-test',children:[node('PriceCalendar'),node('FarePicker')]}]));labelOnly.input.title='New wording';labelOnly.input.$key='new-key';labelOnly.input.artifactRef='artifact-different';assert.equal(analyzeSource(labelOnly).structuralHash,first.structuralHash);assert.notEqual(analyzeSource(a([node('FarePicker'),node('PriceCalendar')])).structuralHash,first.structuralHash)});
test('typed B graph excludes labels, dates and ref spelling but retains actual grouping/dependency/ordered actions',()=>{const first=b(program),cosmetic=b(program.replaceAll('2026-10-09','2026-10-10').replaceAll('dataset-1hq3nnw','dataset-renamed').replaceAll('$dates','$travelDates').replaceAll('fareQuery','renamedQuery').replaceAll('Calendar-led journey planner','Different heading'));assert.equal(first.valid,true);assert.equal(cosmetic.valid,true);assert.equal(cosmetic.structuralHash,first.structuralHash);assert.equal(cosmetic.layoutHash,first.layoutHash);const grouping=b(program.replace('"groupBy":["serviceDate"]','"groupBy":["mode"]'));assert.notEqual(grouping.axes.grouping,first.axes.grouping);const case0=readFileSync('verification/generative-ui/b/live/program-0.openui','utf8');assert.notEqual(b(case0).structuralHash,first.structuralHash);assert.notEqual(b(case0.replace('@Run(reveal), @Set($show, true)','@Set($show, true), @Run(reveal)')).axes.conditionalAction,b(case0).axes.conditionalAction)});
test('same-layout policy-only cells retain validity while receiving no invented novelty',()=>{const analysis=b(program),record=wording=>({scenario:'calendar',cache:'cold',variant:'b',wording,liveModelAuthorship:true,runtimeValid:true,outcome:'pass',acceptedSourceAnalysis:[analysis],targetAcceptedSourceAnalysis:[analysis]});const result=analyzeAuthorshipCorpus([record('fixed'),record('withheld')]);assert.equal(result.fixedWithheld[0].materialGraphChange,false);assert.equal(result.fixedWithheld[0].cellValidityIndependentOfNovelty,true);assert.equal(result.status,'partial-corpus');assert.equal(result.passed,false)});

test('A capability counts exclude only reordered hierarchy while genuine different grouping counts',()=>{const first=analyzeSource(a([node('PriceCalendar'),node('FarePicker')])),reordered=analyzeSource(a([node('FarePicker'),node('PriceCalendar')])),nested=analyzeSource(a([{$type:'Section',artifactRef:'artifact-test',children:[node('PriceCalendar'),node('FarePicker')]}])),record=analysis=>({variant:'a',liveModelAuthorship:true,runtimeValid:true,outcome:'pass',acceptedSourceAnalysis:[analysis]});assert.notEqual(first.layoutHash,reordered.layoutHash);assert.equal(first.compositionHash,reordered.compositionHash);assert.equal(analyzeAuthorshipCorpus([record(first),record(reordered),record(nested)]).counts.aDistinctRecursiveCompositions,2)});
test('B canonical root is the declared root rather than the last statement; conditional titles are cosmetic',()=>{const lines=program.trim().split('\n'),root=lines.pop(),reordered=[root,...lines].join('\n');assert.equal(b(reordered).valid,true);assert.equal(b(reordered).structuralHash,b(program).structuralHash);assert.equal(b(program.replaceAll('Show journey timeline','Display a timeline').replaceAll('Hide journey timeline','Close the timeline')).structuralHash,b(program).structuralHash)});
test('B typed JSON arguments retain fields/operators while ignoring dates and resource aliases',()=>{const query={version:1,sources:[{datasetRef:'dataset-test',alias:'fares'}],where:{field:'serviceDate',op:'eq',value:'2026-10-09'},groupBy:['serviceDate'],metrics:[{as:'minimum',op:'min',field:'priceCents'}],limit:7};const scene=value=>`q = Query("local_query", ${JSON.stringify(JSON.stringify(value))})\ncalendar = PriceCalendar("artifact-test", "dataset-test", null, null, "Days", null, null, null, null, q)\nroot = TravelSurface("artifact-test", "dataset-test", null, null, "Travel", null, [calendar])`;const first=b(scene(query));assert.equal(first.valid,true);assert.equal(b(scene({...query,where:{...query.where,value:'2026-10-10'}})).structuralHash,first.structuralHash);assert.notEqual(b(scene({...query,where:{...query.where,op:'gte'}})).structuralHash,first.structuralHash);assert.notEqual(b(scene({...query,groupBy:['mode']})).axes.grouping,first.axes.grouping)});

test('timeline reveal controls are derived from authored state writes rather than unrelated buttons',()=>{assert.deepEqual(timelineRevealActions({variant:'b',source:program})[0].titles.sort(),['Hide journey timeline','Show journey timeline']);assert.deepEqual(timelineRevealActions({variant:'b',source:readFileSync('verification/generative-ui/b/live/program-0.openui','utf8')}),[])});

test('unreachable declarations cannot inflate genuine B graph novelty',()=>{const unused='$unused = false\nunused = Query("local_query", {"version":1,"sources":[{"datasetRef":"dataset-other","alias":"other"}],"metrics":[{"as":"unusedValue","op":"min","field":"priceCents"}],"limit":1})\n';assert.equal(b(unused+program).valid,true);assert.equal(b(unused+program).structuralHash,b(program).structuralHash)});

test('B layout-only ordering changes remain observable without becoming a new typed graph',()=>{const first=b(program),reordered=b(program.replace('[hero, calendarStory, selectionPane, toggle,','[hero, selectionPane, calendarStory, toggle,'));assert.equal(reordered.valid,true);assert.notEqual(reordered.layoutHash,first.layoutHash);assert.equal(reordered.structuralHash,first.structuralHash)});
